// ÁREA: Fuentes y monitoreo.
//
// REGLA DE ORO: las 4 opciones van del MISMO largo (tolerancia ±5 caracteres).
// Validar con `python check_banco.py`. Ver juego/CONTENIDO.md.

export const FUENTES = [

  // ───────────────────────── SBIR y bordes ─────────────────────────
  {
    id: "fte-sbir-empotrar",
    cat: "SBIR", dif: 2,
    q: "¿Por qué empotrar los monitores (soffit) resuelve el SBIR de esa pared?",
    opts: [
      "Porque la pared absorbe la reflexión que genera el nulo.",
      "Con d→0, el nulo en c/(4d) se va fuera de la banda útil.",
      "Porque aleja el monitor de la posición real de escucha.",
      "Porque elimina los modos axiales del eje frontal largo.",
    ],
    ans: 1,
    why: "El nulo del SBIR está en <code>f = c/(4d)</code>. Si <code>d → 0</code>, <code>f → ∞</code>: el nulo se va de la banda problemática. Además el monitor pasa a radiar en <b>medio espacio (2π)</b> de forma controlada, ganando ~6 dB de acople y una carga predecible en graves. El precio es constructivo: el frente empotrado tiene que ser rígido, masivo y estar bien sellado, o aparecen resonancias nuevas.",
    src: "Toole, Sound Reproduction, §13.2, p. 201 · Newell, Recording Studio Design",
  },
  {
    id: "fte-sbir-peor",
    cat: "SBIR", dif: 3,
    q: "Un monitor a 0,9 m de la pared de atrás. ¿Cuál es el problema, y qué NO lo arregla?",
    opts: [
      "Nulo en ~95 Hz; no lo arregla ni más volumen ni un boost de EQ.",
      "Nulo en ~190 Hz; se arregla con un boost de EQ a esa frecuencia.",
      "No hay problema: 0,9 m es justo la distancia óptima de montaje.",
      "Nulo en ~380 Hz; se corrige alejando al oyente de esa pared.",
    ],
    ans: 0,
    why: "<code>f = c/(4·0,9) ≈ 95 Hz</code>, justo en la zona más comprometida. Lo importante es <b>por qué el EQ no sirve</b>: el nulo es una cancelación por interferencia, y en ese punto el directo y la reflexión se restan casi por completo. Meter boost sube los dos por igual y el nulo sigue ahí — lo único que lográs es quemar excursión y headroom del woofer. Un nulo por interferencia se resuelve con <b>geometría</b> (mover la fuente) o <b>absorción</b> (matar la reflexión), nunca con ganancia.",
    src: "Toole, Sound Reproduction, §13.2, p. 201 · Newell, Recording Studio Design",
  },
  {
    id: "fte-medio-espacio",
    cat: "Carga de bordes", dif: 2,
    q: "Poner un woofer omnidireccional contra una pared (medio espacio)…",
    opts: [
      "Sube el nivel unos 6 dB en la banda donde es omni.",
      "Baja el nivel unos 3 dB por absorción de la pared.",
      "No cambia el nivel, sólo la fase de la radiación.",
      "Sube el nivel unos 20 dB por acople con la pared.",
    ],
    ans: 0,
    why: "La fuente entrega la misma energía en la mitad del ángulo sólido: la presión se duplica, o sea <b>+6 dB</b>. Cada límite adicional suma otros 6 (esquina de dos paredes: +12; triedro: +18). Vale sólo donde el woofer es realmente omnidireccional, o sea en graves — por eso el acople de bordes desbalancea el espectro y hay que compensarlo. Es el mismo mecanismo que hace que un sub en una esquina «rinda más».",
    src: "Toole, Sound Reproduction, cap. 13 · Everest, Master Handbook of Acoustics",
  },
  {
    id: "fte-consola-reflexion",
    cat: "SBIR", dif: 2,
    q: "La reflexión en la superficie de la consola o el escritorio…",
    opts: [
      "Produce un filtro peine en medios, difícil de tratar.",
      "Es despreciable porque la consola es muy pequeña.",
      "Sólo afecta a los graves, por el tamaño del mueble.",
      "Mejora la imagen estéreo al reforzar el directo.",
    ],
    ans: 0,
    why: "Es una reflexión especular con un retardo de pocos ms respecto del directo: interfiere y arma un peine en medios y medios-agudos, justo donde el oído es más sensible. Es de los problemas más subestimados y más difíciles de resolver, porque la superficie tiene que estar ahí. Se mitiga inclinando la consola, bajando la mesa, o eligiendo la altura y el ángulo del monitor para que la reflexión no apunte al oyente.",
    src: "Newell, Recording Studio Design · Toole, Sound Reproduction, §13.2, p. 201",
  },

  // ───────────────────────── Corregibilidad ─────────────────────────
  {
    id: "fte-eq-picos-nulos",
    cat: "Corregibilidad", dif: 3,
    q: "¿Por qué un EQ puede domar un pico modal pero no rellenar un nulo?",
    opts: [
      "Porque los EQ paramétricos sólo tienen filtros de atenuación.",
      "El pico es exceso de energía; el nulo, cancelación espacial.",
      "Porque los nulos no son audibles y no hace falta corregirlos.",
      "Porque el nulo es de fase y el EQ sólo modifica la amplitud.",
    ],
    ans: 1,
    why: "Es la asimetría central de la corregibilidad. Un pico = un modo con Q alto acumulando energía: bajar la excitación a esa frecuencia funciona. Un nulo = dos caminos que llegan en contrafase y se cancelan: si subís la fuente, subís <b>ambos</b> caminos y la resta sigue dando ~cero, sólo consumís headroom. La opción que culpa a la fase es tentadora pero incompleta: un EQ de fase mínima sí toca la fase. El problema real es que la cancelación es <b>espacial</b>, no un defecto de la señal. Se ataca moviendo fuente/oyente, con absorción, o con múltiples subs.",
    src: "Toole, Sound Reproduction, §13.4, p. 239 · Welti & Devantier (2006)",
  },
  {
    id: "fte-eq-fase-minima",
    cat: "Corregibilidad", dif: 3,
    q: "Un EQ de fase mínima corrige bien…",
    opts: [
      "Los picos modales, que son de fase mínima también.",
      "Cualquier nulo, si se aplica suficiente ganancia.",
      "Las reflexiones tempranas de las paredes laterales.",
      "El decaimiento modal, acortando la cola del modo.",
    ],
    ans: 0,
    why: "Un modo resonante <b>es</b> un sistema de fase mínima: su magnitud y su fase están ligadas, así que un filtro de fase mínima inverso corrige las dos a la vez. Ahí el EQ funciona de verdad. Lo que no puede: rellenar nulos (cancelación espacial) ni borrar una reflexión discreta (eso es fase no-mínima, hay un retardo puro de por medio). Sobre la cola: al bajar el pico, el ringing baja en nivel, pero el Q del modo —o sea la duración— no cambia.",
    src: "Toole, Sound Reproduction, §13.4, p. 239 · Low-Frequency Modal Equalization — referencias/",
  },
  {
    id: "fte-multisub",
    cat: "Subwoofers", dif: 3,
    q: "¿Por qué varios subwoofers bien ubicados mejoran la respuesta en graves?",
    opts: [
      "Porque suman SPL y dan mucho más headroom en la banda grave.",
      "Cada sub excita los modos distinto: baja la varianza espacial.",
      "Porque reducen el RT60 de la sala en toda la banda grave.",
      "Porque cancelan entre sí los modos axiales del eje largo.",
    ],
    ans: 1,
    why: "La clave es que la mejora es <b>espacial</b>, no de nivel. Un sub en un nodo de cierto modo no lo excita; otro en un antinodo sí. Combinándolos con posiciones (y a veces ganancia/fase) elegidas, la suma tiene menos desviación punto a punto: la respuesta se parece más entre butacas. Eso es lo que hace que la corrección posterior tenga sentido — un EQ sirve para todos los oyentes sólo si el error es parecido en todos lados. Más SPL es un efecto colateral, no el objetivo.",
    src: "Welti & Devantier (2006) · Toole, Sound Reproduction, §13.3, p. 217",
  },
  {
    id: "fte-curva-objetivo",
    cat: "Corregibilidad", dif: 3,
    q: "¿Por qué la curva objetivo en sala no es plana sino con pendiente?",
    opts: [
      "Porque el oído responde peor a los graves en la sala.",
      "Porque un parlante plano en cámara mide inclinado en sala.",
      "Porque los micrófonos miden mal en la alta frecuencia.",
      "Porque los amplificadores dan menos potencia en agudos.",
    ],
    ans: 1,
    why: "La razón es de directividad, no de gusto. Un parlante bien diseñado radia casi omni en graves y cada vez más directivo en agudos, así que el campo reverberante que se suma en la medición estacionaria aporta <b>mucho más en graves</b> que en agudos. Un parlante plano en cámara anecoica mide, en sala, con una pendiente descendente natural. Perseguir una curva plana medida en sala te obliga a arruinar el directo — que es lo que el oído realmente juzga.",
    src: "Toole, Sound Reproduction, §13.4, p. 239 · Harman target curve",
  },
  {
    id: "fte-cardioide-sub",
    cat: "Subwoofers", dif: 3,
    q: "Un sub cardioide o dipolar, comparado con uno omnidireccional…",
    opts: [
      "Excita menos la sala porque radia menos hacia atrás.",
      "Da más SPL total con la misma potencia de entrada.",
      "Elimina los modos axiales del eje longitudinal largo.",
      "Sólo funciona por encima de la frecuencia de Schroeder.",
    ],
    ans: 0,
    why: "Al radiar con un patrón direccional, entrega menos energía hacia la pared de atrás y excita menos los modos de ese eje: la respuesta queda más limpia sin tocar la sala. El costo es que <b>tira menos SPL</b> por watt (parte de la energía se cancela a propósito) y necesita más excursión o más cajas. Los modos siguen existiendo — sólo que se los alimenta menos.",
    src: "Toole, Sound Reproduction, §13.3, p. 216 · Low frequency sound field control using CABS — referencias/",
  },

  // ───────────────────────── Ubicación y escucha ─────────────────────────
  {
    id: "fte-distancia-critica",
    cat: "Propagación", dif: 2,
    q: "La distancia crítica de una sala es…",
    opts: [
      "La distancia máxima a la que conviene ubicar los monitores.",
      "Donde el campo directo y el reverberante igualan su nivel.",
      "La separación óptima entre los dos monitores del par estéreo.",
      "La distancia a la que empieza el campo lejano de la fuente.",
    ],
    ans: 1,
    why: "Más cerca que la distancia crítica domina el <b>directo</b> (y vale la ley inversa del cuadrado: −6 dB por duplicación); más lejos domina el <b>reverberante</b> y el nivel se aplana. Depende de la absorción de la sala y de la directividad de la fuente: una fuente más directiva empuja la distancia crítica hacia afuera. Es el argumento físico del <b>near-field monitoring</b>: escuchar dentro de la distancia crítica hace que la sala pese menos en lo que oís.",
    src: "Everest, Master Handbook of Acoustics, p. 87 (critical distance)",
  },
  {
    id: "fte-near-field",
    cat: "Monitoreo", dif: 1,
    q: "Monitorear en near-field sirve porque…",
    opts: [
      "El directo domina: la sala pesa menos en lo que oís.",
      "El campo reverberante refuerza los graves útiles.",
      "Se pueden usar monitores de menor calidad general.",
      "Elimina por completo los modos propios de la sala.",
    ],
    ans: 0,
    why: "Acercándote quedás dentro de la distancia crítica: el directo domina sobre el reverberante y la sala «se oye» menos. Es una forma barata de mejorar lo que escuchás sin tocar la sala. Pero ojo con la letra chica — <b>no funciona en graves</b>: ahí λ es comparable a la sala, el campo es modal y no hay distancia crítica que valga. Podés estar a 80 cm del monitor y seguir oyendo el modo de la sala tal cual.",
    src: "Everest, Master Handbook of Acoustics, p. 87 · Newell, Recording Studio Design",
  },
  {
    id: "fte-campo-cercano",
    cat: "Propagación", dif: 2,
    q: "El campo cercano de una fuente es la región donde…",
    opts: [
      "La presión no sigue la ley inversa del cuadrado.",
      "El nivel cae exactamente 6 dB por duplicación.",
      "Domina el campo reverberante sobre el directo.",
      "La respuesta en frecuencia es perfectamente plana.",
    ],
    ans: 0,
    why: "Muy cerca de la fuente, las contribuciones de las distintas partes del radiador llegan con fases distintas y hay energía reactiva que no se propaga: la presión no cae de forma ordenada y depende de dónde midas. Recién en el <b>campo lejano</b> (a varias veces la dimensión de la fuente y varias λ) la fuente se comporta como puntual y aparece el −6 dB por duplicación. Es por esto que un parlante grande hay que medirlo de lejos.",
    src: "Toole, Sound Reproduction, §18.1.1, p. 366 · Beranek, Acústica",
  },
  {
    id: "fte-triangulo",
    cat: "Monitoreo", dif: 1,
    q: "El triángulo equilátero de escucha estéreo busca…",
    opts: [
      "Que ambos monitores estén a igual distancia y a 60°.",
      "Que los monitores queden lo más separados posible.",
      "Que el oyente quede pegado a la pared de atrás.",
      "Que la distancia sea siempre mayor a tres metros.",
    ],
    ans: 0,
    why: "Con 60° de apertura y distancias iguales, las señales de L y R llegan al oyente con los retardos y niveles que el estéreo asume: ahí el fantasma central se forma nítido y centrado. Abrir más los monitores agranda la imagen pero abre un agujero en el centro; cerrarlos la angosta. Y las distancias tienen que ser <b>iguales</b>: unos pocos centímetros de diferencia ya corren la imagen.",
    src: "Toole, Sound Reproduction · ITU-R BS.775",
  },
  {
    id: "fte-monitor-altura",
    cat: "Monitoreo", dif: 1,
    q: "El tweeter de un monitor debería quedar…",
    opts: [
      "A la altura del oído en la posición de escucha.",
      "Lo más alto posible para ganar directividad.",
      "A la altura del pecho, para no cansar el oído.",
      "Da igual: la directividad vertical es amplia.",
    ],
    ans: 0,
    why: "La directividad <b>vertical</b> de un monitor de dos vías es estrecha e irregular cerca del cruce: fuera del eje vertical aparecen lóbulos y nulos por la interferencia entre woofer y tweeter, que están separados físicamente. Salirse unos pocos grados en vertical ya cambia el timbre. En horizontal el patrón es mucho más amplio y benigno — por eso la altura importa bastante más que unos grados de rotación.",
    src: "Toole, Sound Reproduction, §18.2, p. 372",
  },
  {
    id: "fte-itu-775",
    cat: "Monitoreo", dif: 2,
    q: "La recomendación ITU-R BS.775 define…",
    opts: [
      "Los ángulos de los canales en una configuración 5.1.",
      "El nivel máximo de SPL admisible en sala de mezcla.",
      "La curva objetivo de respuesta en frecuencia en sala.",
      "El RT60 recomendado para posproducción de audio.",
    ],
    ans: 0,
    why: "Fija la geometría del multicanal: frontales a ±30°, surrounds a ±100–120°, todos a igual distancia del punto de escucha y con el mismo tipo de monitor. La idea es que el campo sonoro que se mezcla en un estudio se reproduzca igual en otro. Es geometría de reproducción: el nivel, la curva objetivo y el RT los tratan otras normas y recomendaciones.",
    src: "ITU-R BS.775",
  },

  // ───────────────────────── Subwoofers e integración ─────────────────────────
  {
    id: "fte-cruce-80",
    cat: "Subwoofers", dif: 2,
    q: "El cruce típico sub-satélite en 80 Hz se elige porque…",
    opts: [
      "Es donde el sub deja de localizarse y el satélite rinde.",
      "Es la frecuencia de Schroeder de cualquier sala chica.",
      "Es el límite inferior de la audición humana normal.",
      "Es donde el amplificador entrega su máxima potencia.",
    ],
    ans: 0,
    why: "Es un compromiso entre dos cosas: por debajo de ~80 Hz las pistas direccionales se debilitan (λ ≫ cabeza) y el sub no se delata, y por encima el satélite chico ya trabaja cómodo sin exigirle excursión. Que funcione depende de que el pasabajos <b>corte de verdad</b>: si el sub deja pasar armónicos o distorsión arriba del cruce, se localiza igual y se escucha «el sub» como objeto separado.",
    src: "Toole, Sound Reproduction, §13.3, p. 216 · ITU-R BS.775",
  },
  {
    id: "fte-alineacion-fase",
    cat: "Subwoofers", dif: 2,
    q: "Alinear en fase un sub con los monitores en el cruce evita…",
    opts: [
      "Un nulo por cancelación justo en la zona del cruce.",
      "Que el sub se localice como fuente independiente.",
      "La distorsión armónica del woofer en graves altos.",
      "Que el amplificador entre en protección térmica.",
    ],
    ans: 0,
    why: "En la zona de cruce las dos fuentes entregan energía comparable. Si llegan en contrafase al punto de escucha se restan y aparece un agujero — típicamente el «me falta cuerpo en 80 Hz» que ningún EQ arregla, porque es cancelación. Se corrige con el control de fase/polaridad o con delay, y se verifica midiendo: sumás y comparás contra cada fuente sola. Es de los ajustes más rentables de un sistema con sub.",
    src: "Toole, Sound Reproduction, §13.3, p. 216",
  },
  {
    id: "fte-bass-management",
    cat: "Subwoofers", dif: 2,
    q: "El bass management en un sistema multicanal…",
    opts: [
      "Deriva los graves de todos los canales a un sub.",
      "Es lo mismo que el canal LFE de la banda sonora.",
      "Aplica un EQ de graves a cada canal por separado.",
      "Limita el nivel de graves para proteger el sub.",
    ],
    ans: 0,
    why: "Filtra los graves de cada canal principal y los suma al subwoofer, para que los satélites no tengan que reproducir lo que no pueden. Es <b>independiente</b> del canal LFE: el sub termina reproduciendo la suma de los graves derivados <i>más</i> el LFE. Confundirlos es el error clásico — un sistema puede tener bass management sin LFE (música estéreo con sub) y viceversa.",
    src: "Toole, Sound Reproduction, §13.3, p. 216 · ITU-R BS.775",
  },
  {
    id: "fte-lfe",
    cat: "Subwoofers", dif: 2,
    q: "El canal LFE (.1) de un sistema 5.1…",
    opts: [
      "Es un canal aparte con 10 dB de headroom extra.",
      "Es exactamente el mismo canal que el subwoofer.",
      "Contiene los graves derivados de los otros cinco.",
      "Va siempre por encima de los 120 Hz de la banda.",
    ],
    ans: 0,
    why: "El LFE es un canal <b>discreto</b> de banda limitada (~120 Hz), pensado para efectos de mucha energía, y se calibra con +10 dB de headroom respecto de los canales principales. No es «el sub»: el subwoofer es un <i>parlante</i>, que suele reproducir el LFE más los graves que le deriva el bass management. Un sistema puede tener sub sin LFE, y el LFE se puede reproducir sin sub dedicado.",
    src: "Toole, Sound Reproduction, §13.3, p. 216 · ITU-R BS.775",
  },

  // ───────────────────────── Diseño de la fuente ─────────────────────────
  {
    id: "fte-directividad",
    cat: "Directividad", dif: 2,
    q: "¿Por qué importa que un monitor tenga directividad constante con la frecuencia?",
    opts: [
      "Para que el monitor entregue más SPL sobre el eje de escucha.",
      "Fuera de eje se excita la sala: si varía, el reflejado desentona.",
      "Porque de ese modo la sala no desarrolla modos axiales fuertes.",
      "Porque mejora la respuesta transitoria del woofer y el tweeter.",
    ],
    ans: 1,
    why: "Lo que oís es directo + sala, y la sala se alimenta de <b>todo</b> lo que radia el parlante, no sólo del eje. Si el woofer es omnidireccional en graves y el tweeter estrecho en agudos, el campo reverberante sale con exceso de graves respecto del directo. Por eso Toole insiste en juzgar un parlante por su familia completa de curvas (on-axis, listening window, early reflections, sound power) y no por la respuesta en eje sola: dos parlantes con el mismo eje pueden sonar muy distinto en la misma sala.",
    src: "Toole, Sound Reproduction, §18.2, p. 372 (Objective Evaluations)",
  },
  {
    id: "fte-directividad-q",
    cat: "Directividad", dif: 2,
    q: "El factor de directividad Q de una fuente…",
    opts: [
      "Es la relación entre la intensidad en eje y la media.",
      "Es el ángulo de cobertura nominal medido en grados.",
      "Es la impedancia de radiación que ve el diafragma.",
      "Es la potencia acústica total que entrega la fuente.",
    ],
    ans: 0,
    why: "<code>Q</code> compara la intensidad en el eje contra la que habría si la misma potencia se repartiera en todas las direcciones. Q = 1 es omnidireccional; Q = 2, medio espacio. El <b>índice de directividad</b> es su versión en dB: <code>DI = 10·log₁₀(Q)</code>. Es el número que entra en el cálculo de distancia crítica: más Q, más lejos llega el dominio del campo directo.",
    src: "Beranek, Acústica, p. 96 (índice de directividad) · Everest, Master Handbook of Acoustics",
  },
  {
    id: "fte-listening-window",
    cat: "Directividad", dif: 3,
    q: "La «listening window» de Toole es…",
    opts: [
      "El promedio de curvas en un abanico alrededor del eje.",
      "La ventana de vidrio entre control y sala de grabación.",
      "El rango de frecuencias donde el monitor es plano.",
      "La zona de la sala libre de reflexiones tempranas.",
    ],
    ans: 0,
    why: "Es un promedio espacial de la respuesta en un abanico de ±30° horizontal y ±10° vertical: representa lo que efectivamente oye una cabeza que se mueve un poco, en vez de la ficción del eje exacto. Es una de las curvas del «spinorama» (junto con early reflections y sound power), y correlaciona mucho mejor con la preferencia de los oyentes que la respuesta en eje sola.",
    src: "Toole, Sound Reproduction, §18.2, p. 373 · ANSI/CTA-2034",
  },
  {
    id: "fte-waveguide",
    cat: "Directividad", dif: 2,
    q: "Una guía de onda (waveguide) en un tweeter sirve para…",
    opts: [
      "Controlar la directividad y emparejarla con el woofer.",
      "Aumentar la potencia máxima que soporta el tweeter.",
      "Bajar la frecuencia de resonancia propia de la cúpula.",
      "Eliminar la distorsión armónica en alta frecuencia.",
    ],
    ans: 0,
    why: "El problema a resolver es la <b>discontinuidad de directividad</b> en el cruce: el woofer se vuelve directivo justo antes de cruzar, y el tweeter arranca ancho. Eso mete un salto en la energía que va a la sala, aunque el eje mida plano. La guía estrecha el patrón del tweeter en la zona de cruce y empareja la transición. Suele dar de yapa algo de ganancia y menos excursión, pero ése no es su propósito.",
    src: "Toole, Sound Reproduction, §18.2, p. 372",
  },
  {
    id: "fte-mtm-lobing",
    cat: "Directividad", dif: 3,
    q: "Un monitor con dos woofers y el tweeter al medio (MTM) vertical…",
    opts: [
      "Controla la directividad vertical y reduce el lobing.",
      "Duplica la directividad horizontal de la caja usada.",
      "Elimina la necesidad de cruce entre woofer y tweeter.",
      "Sólo funciona bien si el monitor se coloca acostado.",
    ],
    ans: 0,
    why: "La disposición simétrica (D'Appolito) hace que los lóbulos de interferencia entre los dos woofers y el tweeter se distribuyan de forma simétrica arriba y abajo del eje, en vez de inclinar el lóbulo principal como pasa en una caja de dos vías común. El patrón vertical se angosta de manera controlada. Y por eso mismo <b>no</b> hay que acostarlo: acostado, el patrón angosto queda en horizontal, que es justo donde lo querés ancho.",
    src: "Toole, Sound Reproduction, §18.2, p. 372 · D'Appolito (1983)",
  },
  {
    id: "fte-baffle-step",
    cat: "Diseño de caja", dif: 3,
    q: "El baffle step de una caja acústica es…",
    opts: [
      "La transición de 4π a 2π al subir en frecuencia.",
      "El escalón que produce el filtro de cruce agudo.",
      "La resonancia de la caja en su frecuencia de tuning.",
      "El salto de impedancia en la zona del crossover.",
    ],
    ans: 0,
    why: "En graves, λ es mucho mayor que el frente de la caja: el sonido «dobla» alrededor y radia en esfera completa (4π). En agudos, λ es chica frente al baffle y la radiación queda hacia adelante (2π). La transición vale <b>6 dB</b> y ocurre donde λ es comparable al ancho del frente. Por eso las cajas chicas suenan flacas si no se compensa, y por eso el mismo parlante empotrado en pared cambia por completo su balance.",
    src: "Toole, Sound Reproduction, §18.1, p. 366 · Beranek & Mellow, Sound Fields and Transducers, cap. 4, p. 129",
  },
  {
    id: "fte-difraccion-bordes",
    cat: "Diseño de caja", dif: 2,
    q: "Las aristas vivas del gabinete de un monitor…",
    opts: [
      "Difractan y ensucian la respuesta con ondulaciones.",
      "Mejoran la directividad al recortar la radiación.",
      "Sólo afectan por debajo de la frecuencia de cruce.",
      "No influyen: la difracción sólo ocurre en graves.",
    ],
    ans: 0,
    why: "Cada arista se comporta como una <b>fuente secundaria</b> retardada: su radiación interfiere con la del driver y arma ondulaciones en la respuesta y en el patrón de directividad. Por eso los monitores buenos tienen los cantos redondeados o biselados y el tweeter descentrado. Es un efecto de medios y agudos, donde λ es comparable al tamaño de la caja — en graves la caja es acústicamente diminuta.",
    src: "Toole, Sound Reproduction, §18.2, p. 372 · Beranek & Mellow, Sound Fields and Transducers, cap. 4, p. 129",
  },
  {
    id: "fte-sellada-ported",
    cat: "Diseño de caja", dif: 3,
    q: "Frente a una caja sellada, una bass-reflex con el mismo woofer…",
    opts: [
      "Extiende los graves pero con más retardo de grupo.",
      "Tiene menos retardo de grupo y mejor transitorio.",
      "Da exactamente la misma respuesta, con más SPL.",
      "No necesita amplificación adicional en la banda.",
    ],
    ans: 0,
    why: "El puerto es un resonador que aporta salida cerca de la sintonía: extiende la respuesta y alivia la excursión del woofer. El costo es que la caída pasa de 12 dB/oct (sellada, 2º orden) a 24 dB/oct (reflex, 4º orden), y ese orden más alto trae más <b>retardo de grupo</b> cerca de la sintonía. Debajo del tuning, además, el woofer se queda sin carga y desprotegido. Ninguna es «mejor»: es un canje entre extensión, SPL y comportamiento temporal.",
    src: "Beranek & Mellow, Sound Fields and Transducers, cap. 7 (Loudspeaker Enclosures), p. 289 · Toole, Sound Reproduction",
  },
  {
    id: "fte-port-noise",
    cat: "Diseño de caja", dif: 2,
    q: "El ruido de puerto (chuffing) en una caja bass-reflex…",
    opts: [
      "Aparece a alto nivel por velocidad de aire excesiva.",
      "Es la resonancia del puerto en su frecuencia de tuning.",
      "Se produce sólo en cajas selladas, no en las ported.",
      "Baja cuando aumenta el nivel de graves reproducido.",
    ],
    ans: 0,
    why: "A niveles altos el aire pasa tan rápido por el puerto que el flujo se vuelve turbulento y se oye un soplido, sumado a distorsión. Se combate con puertos de mayor área (baja la velocidad para el mismo caudal), bordes acampanados (flared) que evitan el desprendimiento, o puertos múltiples. Es un límite <b>no lineal</b>: no aparece en la medición de respuesta a bajo nivel, sólo cuando exigís la caja.",
    src: "Beranek & Mellow, Sound Fields and Transducers, cap. 7 (Loudspeaker Enclosures), p. 289",
  },
  {
    id: "fte-line-array",
    cat: "Directividad", dif: 3,
    q: "Un line array bien diseñado, en su campo cercano…",
    opts: [
      "Radia onda cilíndrica: cae 3 dB por duplicación.",
      "Radia onda esférica: cae 6 dB por duplicación.",
      "No pierde nivel con la distancia en ningún caso.",
      "Sólo funciona por debajo de los 100 Hz de banda.",
    ],
    ans: 0,
    why: "Una línea de fuentes lo bastante larga y con separación ≪ λ genera un frente <b>cilíndrico</b>: la energía se reparte en la superficie de un cilindro (∝ r) y no de una esfera (∝ r²), así que cae 3 dB por duplicación en vez de 6. Eso vale sólo en el campo cercano de la línea, cuya extensión depende de la longitud y la frecuencia; más lejos vuelve a comportarse como fuente puntual y a caer 6 dB.",
    src: "Toole, Sound Reproduction, §18.1.2, p. 368 · Beranek & Mellow, Sound Fields and Transducers, cap. 4",
  },

  // ───────────────────────── Medición y límites ─────────────────────────
  {
    id: "fte-lede-rfz",
    cat: "Salas de control", dif: 2,
    q: "¿Cuál es la idea central de LEDE / RFZ en una sala de control?",
    opts: [
      "Hacer la sala lo más muerta posible en toda la banda audible.",
      "Directo primero, sin reflexiones tempranas; cola difusa atrás.",
      "Cubrir todas las superficies con difusores de fase cuadrática.",
      "Eliminar los modos propios por debajo de la f de Schroeder.",
    ],
    ans: 1,
    why: "LEDE (Live End Dead End) y RFZ (Reflection Free Zone) atacan las <b>reflexiones tempranas</b>, que se funden perceptualmente con el directo (efecto de precedencia) y corrompen timbre e imagen sin oírse como eco. La receta: frente controlado geométricamente para que la reflexión no vuelva a la posición de escucha, y fondo vivo pero <b>difuso</b>, que sostiene una cola densa y sin dirección definida. No es hacer la sala muerta: una sala anecoica es incómoda y engañosa para mezclar.",
    src: "Newell, Recording Studio Design · Everest, Master Handbook of Acoustics, p. 431 (LEDE/RFZ)",
  },
  {
    id: "fte-medicion-gated",
    cat: "Medición", dif: 3,
    q: "Una medición gated (con ventana) de un monitor en sala…",
    opts: [
      "Pierde resolución en graves: la ventana es muy corta.",
      "Elimina los modos y da la respuesta anecoica real.",
      "Mejora la precisión justamente en la banda grave.",
      "Sólo sirve si la sala tiene RT60 mayor a un segundo.",
    ],
    ans: 0,
    why: "La ventana corta la respuesta al impulso antes de que lleguen las reflexiones, así que «simula» una cámara anecoica. Pero la ventana impone un límite: si podés ventanear 5 ms, la resolución en frecuencia es ~1/5 ms = 200 Hz, o sea que <b>abajo de ~200 Hz la medición no vale nada</b>. Y en una sala chica la primera reflexión llega enseguida, dejando ventanas cortísimas. Justamente donde más problemas hay —los graves— es donde el gating no ayuda.",
    src: "Toole, Sound Reproduction, §18.2.2, p. 376",
  },
  {
    id: "fte-klippel-nfs",
    cat: "Medición", dif: 3,
    q: "Un escáner de campo cercano (NFS) resuelve…",
    opts: [
      "Medir anecoico en graves sin cámara anecoica.",
      "Eliminar la distorsión armónica del parlante.",
      "Medir el RT60 de una sala con más precisión.",
      "Calibrar la respuesta del micro de medición.",
    ],
    ans: 0,
    why: "Muestrea el campo sobre una superficie cerrada alrededor de la caja y, con una expansión en armónicos esféricos, separa matemáticamente lo que radia la fuente de lo que aporta la sala. Así obtiene la respuesta anecoica completa —incluidos los graves— en una sala normal, que es justo lo que ni el gating ni una cámara anecoica chica pueden dar. Es la razón por la que hoy hay tantos datos de spinorama disponibles.",
    src: "Klippel & Bellmann (2016) · Toole, Sound Reproduction, §18.2.2, p. 376",
  },
  {
    id: "fte-thd-imd",
    cat: "Distorsión", dif: 2,
    q: "La distorsión por intermodulación (IMD) en un woofer…",
    opts: [
      "Aparece al reproducir dos tonos y genera sumas y restas.",
      "Es siempre menor que la armónica, en cualquier caso.",
      "Sólo se manifiesta a niveles muy bajos de excursión.",
      "Es idéntica a la THD, sólo que medida de otra forma.",
    ],
    ans: 0,
    why: "Con dos tonos, una no linealidad genera productos en <b>f₂ ± f₁</b> y sus combinaciones. La diferencia perceptual con la THD es clave: los armónicos caen en frecuencias musicalmente relacionadas con el original y se enmascaran bastante, mientras que los productos de intermodulación caen en <b>lugares no relacionados</b> y se oyen como suciedad. Por eso un woofer con THD baja puede sonar sucio si su IMD es alta.",
    src: "Beranek & Mellow, Sound Fields and Transducers, cap. 6, p. 241 · Toole, Sound Reproduction",
  },
  {
    id: "fte-compresion",
    cat: "Distorsión", dif: 2,
    q: "La compresión de potencia en un parlante a alto SPL…",
    opts: [
      "Sube la Re de la bobina al calentarse y baja el nivel.",
      "Es un efecto del compresor de la consola de mezcla.",
      "Mejora la respuesta transitoria por amortiguamiento.",
      "Sólo ocurre en tweeters, nunca en woofers grandes.",
    ],
    ans: 0,
    why: "La bobina se calienta, su resistencia sube (el cobre tiene coeficiente térmico positivo) y el mismo voltaje entrega menos corriente: el parlante rinde menos. Puede llegar a varios dB en uso exigido, y aparece <b>lentamente</b>, así que no la ves en una medición corta. Además cambia el amortiguamiento y con eso el Q del sistema, o sea que el balance tonal se corre a medida que el sistema se calienta.",
    src: "Beranek & Mellow, Sound Fields and Transducers, cap. 6, p. 241",
  },
  {
    id: "fte-sensibilidad",
    cat: "Especificaciones", dif: 2,
    q: "La sensibilidad de un parlante (dB SPL a 2,83 V y 1 m)…",
    opts: [
      "No es lo mismo que eficiencia: depende de la impedancia.",
      "Es exactamente lo mismo que la eficiencia en porcentaje.",
      "Mide la potencia acústica total en todas las direcciones.",
      "Sólo tiene sentido para parlantes de 8 ohms nominales.",
    ],
    ans: 0,
    why: "2,83 V son 1 W <b>sólo en 8 Ω</b>. En un parlante de 4 Ω, esos mismos 2,83 V entregan 2 W, así que la sensibilidad «gana» 3 dB sin que el parlante sea más eficiente. La eficiencia real es potencia acústica sobre potencia eléctrica (típicamente 0,5–2 %, deprimente). Es una de las especificaciones más usadas para inflar planillas: comparar sensibilidades entre impedancias distintas no dice nada.",
    src: "Beranek & Mellow, Sound Fields and Transducers, cap. 6, p. 241 · Toole, Sound Reproduction, §18.6, p. 418",
  },
  {
    id: "fte-impedancia-minima",
    cat: "Especificaciones", dif: 2,
    q: "El mínimo de impedancia de un parlante importa porque…",
    opts: [
      "Es donde el amplificador entrega más corriente.",
      "Es donde el parlante suena con más distorsión.",
      "Coincide siempre con la resonancia del woofer.",
      "Marca la frecuencia de cruce entre las dos vías.",
    ],
    ans: 0,
    why: "El amplificador ve una carga, y donde la impedancia cae la corriente que tiene que entregar sube para el mismo voltaje. Un «8 Ω nominal» con mínimos de 3 Ω y fase muy reactiva es una carga exigente, y ahí es donde un amplificador flojo se queda sin nafta o distorsiona. Ojo con el error de la última opción: en la <b>resonancia</b> del woofer la impedancia tiene un <i>máximo</i>, no un mínimo.",
    src: "Toole, Sound Reproduction, §18.6, p. 418 · Beranek & Mellow, Sound Fields and Transducers, cap. 6, p. 241",
  },
  {
    id: "fte-retardo-grupo",
    cat: "Distorsión", dif: 3,
    q: "El retardo de grupo en graves se vuelve audible…",
    opts: [
      "Cuando supera aproximadamente un ciclo de la señal.",
      "Siempre: cualquier retardo de grupo se oye enseguida.",
      "Sólo en sistemas de más de 1000 W de potencia real.",
      "Nunca, porque el oído es totalmente sordo a la fase.",
    ],
    ans: 0,
    why: "Los umbrales medidos rondan el orden de un ciclo a la frecuencia en cuestión (varias decenas de ms en graves), y son bastante tolerantes: el oído es mucho menos sensible a la fase que a la magnitud. Ni «siempre» ni «nunca». Ese margen es lo que hace viables las cajas reflex y los filtros de orden alto — el retardo de grupo que introducen suele quedar por debajo del umbral con material musical real.",
    src: "Toole, Sound Reproduction, §18.6.2, p. 420 · Blauert & Laws (1978)",
  },

].map((q) => ({ ...q, area: "fuentes" }));
