// ÁREA: Psicoacústica.
//
// REGLA DE ORO: las 4 opciones van del MISMO largo (tolerancia ±5 caracteres).
// Validar con `python check_banco.py`. Ver juego/CONTENIDO.md.

export const PSICOACUSTICA = [

  // ───────────────────── Bandas críticas y enmascaramiento ─────────────────────
  {
    id: "psi-enmascaramiento",
    cat: "Enmascaramiento", dif: 2,
    q: "El enmascaramiento en frecuencia es asimétrico. ¿En qué sentido?",
    opts: [
      "Un tono enmascara más hacia las frecuencias más bajas.",
      "Un tono enmascara más hacia las frecuencias más altas.",
      "Es simétrico: enmascara igual hacia arriba y hacia abajo.",
      "Sólo enmascara dentro de los límites de su banda crítica.",
    ],
    ans: 1,
    why: "La curva de enmascaramiento se extiende con pendiente suave hacia <b>arriba</b> (upward spread of masking) y es abrupta hacia abajo; la asimetría se acentúa a niveles altos. Sale de la mecánica coclear: la onda viajera recorre la membrana basilar desde la base (agudos) hacia el ápex (graves), así que un tono grave fuerte agita la región de los agudos en su camino. Consecuencia práctica: un exceso de graves en la sala ensucia la inteligibilidad de los medios, no al revés.",
    src: "Zwicker & Fastl, Psychoacoustics, §4.1, p. 62",
  },
  {
    id: "psi-banda-critica",
    cat: "Bandas críticas", dif: 2,
    q: "Una banda crítica es…",
    opts: [
      "El ancho de banda en que el oído integra la energía.",
      "El rango de niveles que el oído tolera sin dolor real.",
      "La banda en la que un parlante entrega su máximo SPL.",
      "El ancho de cada filtro en un ecualizador gráfico.",
    ],
    ans: 0,
    why: "La cóclea se comporta como un banco de filtros solapados: dentro de una misma banda crítica, el oído <b>suma</b> la energía y no distingue los componentes por separado. Es el concepto del que cuelga casi toda la psicoacústica aplicada — enmascaramiento, sonoridad, aspereza — y es la base de la codificación perceptual: MP3 y AAC tiran lo que cae bajo el umbral de enmascaramiento dentro de cada banda.",
    src: "Zwicker & Fastl, Psychoacoustics, §6.1, p. 150",
  },
  {
    id: "psi-bark",
    cat: "Bandas críticas", dif: 2,
    q: "La escala de Bark…",
    opts: [
      "Divide el espectro audible en 24 bandas críticas.",
      "Mide el nivel de presión sonora en dB ponderados.",
      "Es otra forma de expresar la sonoridad en sonios.",
      "Describe la respuesta temporal del oído medio.",
    ],
    ans: 0,
    why: "Es una escala de frecuencia <b>perceptual</b>: cada Bark equivale a una banda crítica, y las 24 cubren de 20 Hz a ~15,5 kHz. Su gracia es que distancias iguales en Barks corresponden a distancias iguales sobre la membrana basilar, lo que no pasa con los Hz. Por eso los modelos de sonoridad y de enmascaramiento trabajan en Barks (o en ERB) y no en escala lineal de frecuencia.",
    src: "Zwicker & Fastl, Psychoacoustics, §6.2 (critical-band rate/Bark), p. 158",
  },
  {
    id: "psi-erb",
    cat: "Bandas críticas", dif: 3,
    q: "El ERB (Equivalent Rectangular Bandwidth), frente a la escala de Bark…",
    opts: [
      "Da bandas más angostas en las frecuencias bajas.",
      "Da bandas más anchas justo en frecuencias bajas.",
      "Mide exactamente lo mismo, sólo que con otro nombre.",
      "Sólo se aplica por encima de los 5 kHz de banda.",
    ],
    ans: 0,
    why: "El ERB (Moore y Glasberg) sale de experimentos con ruido con muesca, que evitan un sesgo de los ensayos clásicos de Zwicker. El resultado: en graves los filtros auditivos son <b>más selectivos</b> de lo que decía Bark — abajo de 500 Hz la diferencia es grande. Es el modelo que usan hoy los modelos de sonoridad más recientes. No son intercambiables, aunque describan el mismo fenómeno.",
    src: "Moore, An Introduction to the Psychology of Hearing · Glasberg & Moore (1990)",
  },
  {
    id: "psi-enmascaramiento-temporal",
    cat: "Enmascaramiento", dif: 3,
    q: "El enmascaramiento temporal hacia atrás (backward masking)…",
    opts: [
      "Un sonido enmascara a otro que ocurrió ANTES que él.",
      "Un sonido enmascara a otro que viene justo después.",
      "Sólo ocurre entre sonidos de la misma frecuencia.",
      "Dura varios segundos después del sonido enmascarador.",
    ],
    ans: 0,
    why: "Suena imposible —el efecto precede a la causa— pero es real: un sonido fuerte enmascara a otro débil que llegó unos pocos ms <b>antes</b>. Se explica por el tiempo de procesamiento neural: el estímulo intenso «alcanza» al débil en el camino. Es corto (~5–20 ms) frente al forward masking (~100–200 ms). Los códecs perceptuales lo aprovechan para esconder el pre-eco de la transformada.",
    src: "Zwicker & Fastl, Psychoacoustics, §4.4.2 (premasking), p. 82 · Moore",
  },
  {
    id: "psi-bmld",
    cat: "Enmascaramiento", dif: 3,
    q: "La diferencia binaural de nivel de enmascaramiento (BMLD)…",
    opts: [
      "Mejora la detección si señal y ruido difieren en fase.",
      "Es la diferencia de sensibilidad entre los dos oídos.",
      "Aparece sólo si se escucha con un solo oído tapado.",
      "Mide cuánto enmascara un tono a otro tono más agudo.",
    ],
    ans: 0,
    why: "Si un tono está enmascarado por ruido en ambos oídos y se invierte la fase del tono en <b>uno solo</b>, vuelve a ser audible: la ganancia puede llegar a 15 dB. El sistema binaural compara las dos entradas y lo que no correlaciona «salta». Es un mecanismo emparentado con el efecto cóctel, y prueba que el enmascaramiento no es sólo un fenómeno periférico de la cóclea.",
    src: "Zwicker & Fastl, Psychoacoustics, §15.2, p. 295 · Moore · Blauert",
  },
  {
    id: "psi-cocktail",
    cat: "Enmascaramiento", dif: 2,
    q: "El efecto cóctel (cocktail party) se apoya sobre todo en…",
    opts: [
      "La escucha binaural: dos oídos separan las fuentes.",
      "El aumento del nivel de la voz que interesa oír.",
      "La reverberación de la sala, que agrupa fuentes.",
      "El enmascaramiento completo del ruido de fondo.",
    ],
    ans: 0,
    why: "Poder seguir una conversación en un bar depende de tener <b>dos</b> oídos: el sistema binaural usa las diferencias de tiempo y nivel para separar espacialmente las fuentes y suprimir lo que viene de otras direcciones (BMLD es parte del mecanismo). Con un solo oído la tarea se vuelve muy difícil. Por eso una hipoacusia unilateral molesta mucho más en ambientes ruidosos que en silencio.",
    src: "Moore, An Introduction to the Psychology of Hearing · Blauert",
  },

  // ───────────────────── Sonoridad y nivel ─────────────────────
  {
    id: "psi-isofonicas",
    cat: "Sonoridad", dif: 2,
    q: "Las curvas isofónicas (ISO 226) muestran que…",
    opts: [
      "A bajo nivel, el oído pierde sensibilidad en graves.",
      "El oído es igual de sensible en toda la banda audible.",
      "A alto nivel, los graves se perciben más débiles aún.",
      "La sensibilidad máxima del oído está en los 100 Hz.",
    ],
    ans: 0,
    why: "Las curvas se <b>aplanan</b> al subir el nivel: a 90 fon el balance grave-medio es mucho más parejo que a 20 fon. De ahí que una mezcla escuchada bajito parezca sin graves, y que exista el botón «loudness». Y de ahí también un problema real del oficio: mezclar a niveles muy distintos cambia el balance tonal que percibís, lo que hace que el nivel de monitoreo tenga que ser consistente.",
    src: "ISO 226 · Zwicker & Fastl, Psychoacoustics",
  },
  {
    id: "psi-fon-sonio",
    cat: "Sonoridad", dif: 3,
    q: "La diferencia entre fon y sonio es que…",
    opts: [
      "El fon iguala sonoridad contra 1 kHz; el sonio, de razón.",
      "Son sinónimos: dos nombres para la misma unidad de nivel.",
      "El fon mide presión y el sonio mide potencia acústica.",
      "El fon se usa en graves y el sonio en agudos nada más.",
    ],
    ans: 0,
    why: "El <b>fon</b> es un nivel: N fon = tan sonoro como N dB SPL a 1 kHz. Pero no es proporcional a la sensación — 80 fon no suena «el doble» que 40. El <b>sonio</b> sí es una escala de razón: 2 sonios suenan el doble que 1. La relación práctica es que <b>+10 fon ≈ el doble de sonios</b>, o sea que hace falta subir ~10 dB para que algo suene el doble de fuerte. Por eso 3 dB de más «casi no se notan».",
    src: "Zwicker & Fastl, Psychoacoustics, §8.1–8.2 (fon/sonio), p. 203–205",
  },
  {
    id: "psi-sensibilidad-max",
    cat: "Sonoridad", dif: 1,
    q: "El oído humano es más sensible alrededor de…",
    opts: [
      "2–5 kHz, por la resonancia del canal auditivo.",
      "100–200 Hz, donde está el grueso de la energía.",
      "10–15 kHz, donde percibe el brillo y el aire.",
      "500 Hz, el centro geométrico de la banda audible.",
    ],
    ans: 0,
    why: "El conducto auditivo es un tubo de ~2,5 cm cerrado en el tímpano: resuena en λ/4, o sea cerca de 3 kHz, y aporta hasta ~15 dB de ganancia acústica gratis. No es casualidad que ahí vivan las consonantes que dan inteligibilidad, ni que las alarmas y el llanto de un bebé estén sintonizados justo en esa zona. También es la banda que primero se daña por exposición a ruido.",
    src: "Moore, An Introduction to the Psychology of Hearing · ISO 226",
  },
  {
    id: "psi-umbral-audicion",
    cat: "Sonoridad", dif: 1,
    q: "El 0 dB SPL de referencia (20 µPa) corresponde a…",
    opts: [
      "El umbral de audición aproximado, a 1 kHz.",
      "El nivel de dolor en el oído humano medio.",
      "El ruido de fondo de una sala de conciertos.",
      "La presión atmosférica media al nivel del mar.",
    ],
    ans: 0,
    why: "20 µPa se eligió porque aproxima el umbral de audición de un oyente joven <b>a 1 kHz</b>. La letra chica importa: es la referencia de la escala, no el umbral a toda frecuencia — a 50 Hz el umbral real está cerca de 40 dB SPL. Para dimensionarlo: 20 µPa son unas cinco mil millones de veces menos que la presión atmosférica. El oído es un instrumento absurdamente sensible.",
    src: "ISO 226 · Everest, Master Handbook of Acoustics",
  },
  {
    id: "psi-ponderacion-a",
    cat: "Sonoridad", dif: 2,
    q: "La ponderación A de un sonómetro…",
    opts: [
      "Imita la isofónica de 40 fon: subestima graves.",
      "Es plana: no altera en nada el espectro medido.",
      "Imita el oído a niveles altos, cerca de 100 dB.",
      "Sólo se usa para medir ruido de baja frecuencia.",
    ],
    ans: 0,
    why: "La curva A imita la isofónica de <b>40 fon</b>, o sea el oído a nivel bajo, y por eso atenúa fuerte los graves (−16 dB en 125 Hz). El problema: se la usa para todo, incluso a 100 dB, donde el oído responde parecido a la curva C (casi plana). Un ruido con mucha energía grave puede medir «tranquilo» en dB(A) y ser molesto de verdad. Es la crítica clásica a usar un número único.",
    src: "Zwicker & Fastl, Psychoacoustics, §8.7.3 (loudness meters), p. 233 · IEC 61672",
  },
  {
    id: "psi-jnd-nivel",
    cat: "Sonoridad", dif: 2,
    q: "La mínima diferencia de nivel audible (JND) ronda…",
    opts: [
      "1 dB, en condiciones de escucha favorables.",
      "10 dB, por eso el dB se definió en esa escala.",
      "0,01 dB: el oído es un instrumento de precisión.",
      "3 dB, que es la duplicación de la potencia.",
    ],
    ans: 0,
    why: "Cerca de 1 dB comparando A/B directo con material sostenido; con música y de memoria, bastante peor. Dos consecuencias prácticas: un cambio de 0,5 dB en un EQ es probablemente inaudible (y sin embargo se discute mucho), y el clásico truco de las demos —subir 1 dB el equipo que se quiere vender— alcanza para que «suene mejor». Por eso las comparaciones serias se hacen con niveles igualados.",
    src: "Zwicker & Fastl, Psychoacoustics, §7.1.2, p. 180 · Moore · Toole, Sound Reproduction",
  },
  {
    id: "psi-integracion-temporal",
    cat: "Sonoridad", dif: 3,
    q: "El oído integra energía en ventanas de ~200 ms, y por eso…",
    opts: [
      "Un tono corto suena más débil que uno largo igual.",
      "Un tono corto suena más fuerte que uno largo igual.",
      "El RT60 no afecta en nada la sonoridad percibida.",
      "La sonoridad nunca depende de la duración del tono.",
    ],
    ans: 0,
    why: "Debajo de ~200 ms la sonoridad crece con la duración: un impulso de 10 ms se percibe bastante más débil que un tono sostenido del mismo nivel de pico. Pasada la ventana, la sonoridad se estabiliza. Esto explica por qué un pico transitorio corto no se oye tan fuerte como indica el medidor de pico — y es la razón de ser de los medidores con integración lenta y de las escalas de loudness tipo LUFS.",
    src: "Zwicker & Fastl, Psychoacoustics, §8.5 (temporal effects), p. 216",
  },

  // ───────────────────── Localización ─────────────────────
  {
    id: "psi-precedencia",
    cat: "Localización", dif: 2,
    q: "El efecto de precedencia (ley del primer frente de onda) dice que…",
    opts: [
      "El sonido más fuerte determina la dirección que percibimos.",
      "Localizamos según el primer frente, aunque llegue otro igual.",
      "Las reflexiones tempranas de la sala simplemente no se oyen.",
      "El oído promedia las direcciones de todas las reflexiones.",
    ],
    ans: 1,
    why: "Dentro de una ventana de ~1–30 ms, la réplica no se oye como evento separado ni corre la imagen: se <b>funde</b> con el directo y aporta timbre y sensación de espacio. Por eso una reflexión temprana no se percibe como eco pero igual arruina la imagen estéreo y colorea — no es que «no se oiga», es que no se oye <i>por separado</i>. Pasada la ventana aparece el eco discreto. Es la base perceptual de LEDE/RFZ.",
    src: "Everest, Master Handbook of Acoustics, p. 353 (Law of the First Wavefront)",
  },
  {
    id: "psi-localizacion-graves",
    cat: "Localización", dif: 2,
    q: "¿Por qué se dice que los graves «no se localizan»?",
    opts: [
      "Porque el oído es muy poco sensible por debajo de 80 Hz.",
      "λ ≫ cabeza: sin ILD y con ITD ambigua, aunque hay matices.",
      "Porque los subwoofers son omnidireccionales por su diseño.",
      "Porque las ondas graves viajan más lento que las agudas.",
    ],
    ans: 1,
    why: "A 80 Hz, λ ≈ 4,3 m contra una cabeza de ~18 cm: la cabeza no hace sombra, así que la ILD desaparece y quedan pistas débiles. <b>Pero la letra chica importa</b>: si el sub distorsiona o deja pasar contenido arriba del cruce, esos armónicos sí se localizan y delatan la caja. Por eso Toole insiste en que el pasabajos corte de verdad. Que la pista direccional sea débil no significa que el sub sea inaudible como objeto.",
    src: "Toole, Sound Reproduction, cap. 13",
  },
  {
    id: "psi-duplex",
    cat: "Localización", dif: 3,
    q: "La teoría duplex de la localización dice que…",
    opts: [
      "ITD manda en graves e ILD en agudos, cruce a ~1,5 kHz.",
      "ILD manda en graves e ITD en agudos, cruce a ~1,5 kHz.",
      "Sólo la ITD interviene, en toda la banda audible y útil.",
      "La localización depende sólo de la HRTF de cada oyente.",
    ],
    ans: 0,
    why: "Cada pista falla en un extremo. La <b>ITD</b> (diferencia de tiempo) es inequívoca mientras λ sea mayor que la cabeza; arriba de ~1,5 kHz media longitud de onda es menor que la separación de los oídos y la fase se vuelve ambigua. La <b>ILD</b> (diferencia de nivel) necesita que la cabeza haga sombra, y eso sólo pasa en agudos. Cada una cubre donde la otra fracasa. La zona de cruce, alrededor de 1,5–3 kHz, es justamente donde peor localizamos.",
    src: "Rayleigh (1907) · Blauert, Spatial Hearing · Moore",
  },
  {
    id: "psi-hrtf",
    cat: "Localización", dif: 3,
    q: "La HRTF codifica principalmente…",
    opts: [
      "El filtrado de cabeza, torso y pabellón por dirección.",
      "La respuesta en frecuencia del tímpano únicamente.",
      "El retardo entre los dos oídos, y nada más que eso.",
      "La curva de sonoridad para cada nivel de presión.",
    ],
    ans: 0,
    why: "Es la firma direccional completa: cómo el torso, la cabeza y sobre todo los pliegues del pabellón filtran el sonido según de dónde venga. Los picos y valles que introduce el pabellón (por encima de ~5 kHz) son la clave para resolver <b>arriba/abajo</b> y adelante/atrás, que ITD e ILD no pueden. Son muy personales: usar una HRTF ajena es lo que hace que el binaural genérico suene «dentro de la cabeza».",
    src: "Blauert, Spatial Hearing · Principles and Applications of Spatial Hearing — referencias/",
  },
  {
    id: "psi-cono-confusion",
    cat: "Localización", dif: 3,
    q: "El cono de confusión es…",
    opts: [
      "El conjunto de puntos con la misma ITD e ILD.",
      "La zona muerta detrás de la cabeza del oyente.",
      "El ángulo en que la HRTF se vuelve del todo plana.",
      "La región a la que no llega el campo directo.",
    ],
    ans: 0,
    why: "Todas las direcciones sobre ese cono producen <b>exactamente las mismas</b> diferencias interaurales: adelante y atrás, arriba y abajo, se vuelven indistinguibles con ITD e ILD solas. Lo resuelven dos cosas: el filtrado espectral del pabellón (la HRTF) y, sobre todo, <b>mover la cabeza</b> — un pequeño giro rompe la ambigüedad al instante. Es la razón de que el head tracking mejore tanto el binaural.",
    src: "Blauert, Spatial Hearing",
  },
  {
    id: "psi-haas",
    cat: "Localización", dif: 2,
    q: "El umbral de eco (efecto Haas) aparece…",
    opts: [
      "Cuando el retardo pasa los ~30 ms y se oye separado.",
      "Apenas hay 1 ms de retardo entre directo y réplica.",
      "Sólo si la réplica llega más fuerte que el directo.",
      "Cuando la sala tiene un RT60 mayor a dos segundos.",
    ],
    ans: 0,
    why: "Debajo del umbral, la réplica se funde con el directo (precedencia): aporta timbre y espacio pero no se oye aparte. Al pasarlo, se despega y aparece como <b>eco discreto</b>. El valor exacto depende mucho del material: con habla ronda los 30–50 ms, con transitorios secos como castañuelas baja bastante, y con música sostenida sube. No es un número fijo, es un umbral dependiente de la señal.",
    src: "Haas (1951) · Everest, Master Handbook of Acoustics, p. 353",
  },

  // ───────────────────── Salas y espacialidad ─────────────────────
  {
    id: "psi-umbral-modal",
    cat: "Umbrales", dif: 3,
    q: "Según Fazenda et al. (2015), ¿qué determina la percepción de un modo?",
    opts: [
      "Sólo la amplitud del pico en la respuesta estacionaria medida.",
      "El decaimiento modal es determinante, aun con pico moderado.",
      "Los modos no son audibles como tales por debajo de 100 Hz.",
      "Sólo la frecuencia exacta a la que cae el modo en la banda.",
    ],
    ans: 1,
    why: "Es un resultado importante y contraintuitivo: la respuesta en frecuencia estacionaria <b>no alcanza</b> para predecir qué molesta. Un modo con Q alto sostiene la nota en el tiempo (ringing) y se oye como pesadez o como una nota que queda colgada, aunque su pico no sea enorme. De ahí que el tratamiento apunte a bajar el Q (absorción) y no sólo a aplanar la magnitud — y de ahí también que un EQ, que corrige magnitud, no resuelva del todo un modo con cola larga.",
    src: "Fazenda, Stephenson & Goldberg (2015), JASA 137 — referencias/Fazenda*.pdf",
  },
  {
    id: "psi-iacc",
    cat: "Espacialidad", dif: 3,
    q: "El IACC de una sala mide…",
    opts: [
      "La similitud entre las señales de ambos oídos.",
      "El nivel de presión promedio medido en platea.",
      "El tiempo de reverberación a 1 kHz exactamente.",
      "La cantidad de reflexiones tempranas por segundo.",
    ],
    ans: 0,
    why: "Es la correlación cruzada interaural: cuánto se parecen las señales que llegan a cada oído. Un IACC <b>alto</b> (señales parecidas) da una imagen angosta y centrada; uno <b>bajo</b> (señales distintas) da sensación de amplitud y envolvimiento. Por eso las salas de concierto buscan reflexiones laterales tempranas: son las que decorrelacionan los oídos. Una sala «de zapatero» angosta lo logra por geometría.",
    src: "Beranek, Concert Halls and Opera Houses · Ando, Architectural Acoustics",
  },
  {
    id: "psi-asw-lev",
    cat: "Espacialidad", dif: 3,
    q: "ASW (ancho aparente de la fuente) y LEV (envolvimiento) …",
    opts: [
      "Vienen de reflexiones tempranas y tardías, en ese orden.",
      "Son lo mismo, sólo medido con micrófonos diferentes.",
      "Dependen únicamente del RT60 de la sala en cuestión.",
      "Son parámetros que sólo se aplican en salas chicas.",
    ],
    ans: 0,
    why: "Son dos sensaciones distintas con causas distintas. El <b>ASW</b> (la fuente suena más ancha que su tamaño físico) lo generan las reflexiones laterales <b>tempranas</b>, dentro de los primeros ~80 ms. El <b>LEV</b> (estar envuelto por el sonido) lo genera la energía lateral <b>tardía</b>, después de los 80 ms. Por eso una sala puede tener buena imagen y poco envolvimiento, o al revés: se diseñan por separado.",
    src: "Beranek, Concert Halls and Opera Houses · Barron, Auditorium Acoustics",
  },
  {
    id: "psi-sti",
    cat: "Inteligibilidad", dif: 2,
    q: "El STI (Speech Transmission Index) se degrada por…",
    opts: [
      "Reverberación y ruido, que borran la modulación.",
      "Un RT60 demasiado corto en la banda de la voz.",
      "Exceso de directividad en el sistema de refuerzo.",
      "Una respuesta en frecuencia excesivamente plana.",
    ],
    ans: 0,
    why: "El STI parte de una idea elegante: la información del habla está en la <b>envolvente de modulación</b>, no en la portadora. Se mide cuánta profundidad de modulación sobrevive al canal (usando la MTF) y se resume en un índice de 0 a 1. Los dos enemigos son la reverberación, que rellena los valles de la envolvente, y el ruido de fondo, que hace lo mismo. Un RT corto y una fuente directiva <i>mejoran</i> el STI.",
    src: "IEC 60268-16 · Everest, Master Handbook of Acoustics",
  },
  {
    id: "psi-alcons",
    cat: "Inteligibilidad", dif: 2,
    q: "El %ALcons (pérdida de articulación de consonantes)…",
    opts: [
      "Empeora al subir el RT60 y la distancia a la fuente.",
      "Mejora al subir el RT60, por refuerzo de energía.",
      "Sólo depende del nivel de voz del orador en sala.",
      "Es independiente de la reverberación de la sala.",
    ],
    ans: 0,
    why: "Mide qué porcentaje de consonantes se pierde: al revés que el STI, acá <b>menos es mejor</b> (bajo 10 % se considera bueno). Las consonantes son las que llevan la información y son cortas y débiles: la cola reverberante de la vocal anterior las tapa. Y empeora con la distancia porque el directo cae mientras el reverberante se mantiene — pasada la distancia crítica, alejarse casi no cambia el nivel pero sí arruina la inteligibilidad.",
    src: "Peutz (1971) · Everest, Master Handbook of Acoustics",
  },

  // ───────────────────── Altura, timbre y tiempo ─────────────────────
  {
    id: "psi-fundamental-ausente",
    cat: "Altura", dif: 2,
    q: "El fenómeno de la fundamental ausente muestra que…",
    opts: [
      "El oído infiere la altura desde los armónicos.",
      "Los graves no se pueden reproducir sin un sub.",
      "La altura depende sólo de la energía en la f0.",
      "El oído no puede percibir sonidos complejos.",
    ],
    ans: 0,
    why: "Si sacás la fundamental de un tono complejo y dejás sólo los armónicos (200, 300, 400 Hz…), seguís oyendo la altura de 100 Hz: el oído reconstruye el período a partir del espaciado de los parciales. Es la razón por la que un parlante de celular «tiene» graves que físicamente no puede radiar. Y demuestra que la altura no está en el espectro sino en el <b>procesamiento</b> — es una inferencia, no una medición.",
    src: "Moore, An Introduction to the Psychology of Hearing · Roederer, Acústica y Psicoacústica",
  },
  {
    id: "psi-lugar-temporal",
    cat: "Altura", dif: 3,
    q: "La percepción de altura combina teoría de lugar y temporal porque…",
    opts: [
      "El lugar falla en graves; el temporal falla en agudos.",
      "El lugar falla en agudos; el temporal falla en graves.",
      "Las dos teorías quedaron refutadas por completo ya.",
      "Sólo hay una teoría válida: la del lugar en la cóclea.",
    ],
    ans: 0,
    why: "La teoría del <b>lugar</b> (qué zona de la membrana basilar vibra) pierde resolución en graves, donde la envolvente de la onda viajera es ancha y poco selectiva. La <b>temporal</b> (enganche de fase de las fibras nerviosas al período) funciona muy bien en graves pero se cae arriba de ~4–5 kHz, porque las neuronas no pueden seguir esa velocidad. Se complementan — y no por casualidad, arriba de 5 kHz nuestra percepción de melodía se degrada mucho.",
    src: "Moore, An Introduction to the Psychology of Hearing · Roederer",
  },
  {
    id: "psi-aspereza",
    cat: "Timbre", dif: 2,
    q: "La aspereza (roughness) se percibe cuando dos tonos…",
    opts: [
      "Baten a una velocidad de unos 70 Hz de diferencia.",
      "Están separados por más de una octava entre sí.",
      "Tienen exactamente la misma frecuencia y fase.",
      "Suenan a más de 100 dB SPL en la sala tratada.",
    ],
    ans: 0,
    why: "Hay un recorrido según la separación: hasta ~15 Hz de diferencia oís <b>batidos</b> (una fluctuación que podés contar); alrededor de <b>70 Hz</b> la sensación es máxima aspereza; y pasada la banda crítica los tonos se separan y la aspereza desaparece. Es la base psicoacústica de la disonancia: los intervalos disonantes son los que dejan parciales dentro de una misma banda crítica.",
    src: "Zwicker & Fastl, Psychoacoustics, §11.1, p. 257 · Roederer, Acústica y Psicoacústica",
  },
  {
    id: "psi-agudeza",
    cat: "Timbre", dif: 2,
    q: "La agudeza (sharpness) de Zwicker mide…",
    opts: [
      "El peso del contenido agudo en el espectro.",
      "La velocidad de ataque de un transitorio.",
      "La cantidad de distorsión armónica audible.",
      "El nivel de presión sonora en dB(A) medidos.",
    ],
    ans: 0,
    why: "Es el centroide del patrón de sonoridad en la escala de Bark, ponderado para dar más peso a los agudos: se expresa en <b>acum</b>, con la referencia en 1 acum (ruido de banda estrecha en 1 kHz a 60 dB). Es uno de los descriptores de calidad sonora que se usan en la industria (sonido de un motor, de una puerta al cerrarse), donde el dB(A) solo no dice nada sobre si algo suena agradable o molesto.",
    src: "Zwicker & Fastl, Psychoacoustics, §9.1–9.2 (sharpness), p. 239",
  },
  {
    id: "psi-resolucion-temporal",
    cat: "Tiempo", dif: 3,
    q: "La resolución temporal del oído (detección de huecos)…",
    opts: [
      "Ronda los 2–3 ms para un hueco en ruido continuo.",
      "Ronda 1 segundo: el oído integra por mucho tiempo.",
      "Es de microsegundos, como la de la ITD binaural.",
      "No existe: el oído no resuelve el tiempo en absoluto.",
    ],
    ans: 0,
    why: "El detalle interesante es la comparación con la ITD: para detectar un <b>hueco</b> en un ruido hacen falta ~2–3 ms, pero el sistema binaural resuelve diferencias de tiempo entre oídos de ~10 <b>microsegundos</b> — unas 300 veces mejor. No es contradictorio: son mecanismos distintos. Uno es resolución monoaural de envolvente; el otro, comparación de fase entre dos canales, que es muchísimo más fina.",
    src: "Moore, An Introduction to the Psychology of Hearing",
  },
  {
    id: "psi-streaming",
    cat: "Tiempo", dif: 3,
    q: "El análisis de escena auditiva (streaming) explica…",
    opts: [
      "Cómo el oído agrupa parciales en fuentes distintas.",
      "Cómo se mide el RT60 usando ruido interrumpido.",
      "Por qué los graves no se localizan en una sala.",
      "Cómo se calibra un sistema de monitoreo 5.1 real.",
    ],
    ans: 0,
    why: "Bregman: el oído recibe una única mezcla de presión en cada tímpano y tiene que reconstruir cuántas fuentes hay y qué hace cada una. Agrupa por armonicidad, ataque común, continuidad, proximidad en frecuencia. Es el problema que la audición resuelve sin esfuerzo y las máquinas todavía sufren. Y es lo que hace que puedas seguir la línea de bajo en una mezcla densa: no es filtrado, es agrupamiento.",
    src: "Bregman, Auditory Scene Analysis · Moore",
  },

  // ───────────────────── Audición y daño ─────────────────────
  {
    id: "psi-reclutamiento",
    cat: "Audiología", dif: 3,
    q: "El reclutamiento (recruitment) en la hipoacusia coclear…",
    opts: [
      "Sube el umbral pero no el nivel de incomodidad.",
      "Baja el umbral de audición y también el de dolor.",
      "Afecta sólo la percepción de la altura tonal.",
      "Hace que todos los sonidos suenen más suaves.",
    ],
    ans: 0,
    why: "Es lo que hace tan difícil ayudar a un hipoacúsico coclear: el umbral sube (no oye lo bajo) pero el nivel de incomodidad se queda donde estaba, así que el <b>rango dinámico útil se comprime</b>. La sonoridad crece anormalmente rápido con el nivel. De ahí el clásico «no te escucho… ¡no me grites!». Y de ahí que un audífono no pueda ser un simple amplificador: tiene que comprimir.",
    src: "Moore, An Introduction to the Psychology of Hearing · Audiología Básica — referencias/",
  },
  {
    id: "psi-presbiacusia",
    cat: "Audiología", dif: 1,
    q: "La presbiacusia afecta primero…",
    opts: [
      "Las frecuencias agudas, arriba de unos 4 kHz.",
      "Las frecuencias graves, debajo de los 100 Hz.",
      "Toda la banda audible por igual y al mismo tiempo.",
      "Sólo la percepción de altura tonal, no el nivel.",
    ],
    ans: 0,
    why: "La pérdida por edad arranca en agudos y avanza hacia abajo. La razón anatómica es que las células ciliadas de los agudos están en la <b>base</b> de la cóclea, y toda onda viajera —venga de la frecuencia que venga— tiene que pasar por ahí: acumulan más desgaste. Es la misma zona que castiga la exposición a ruido, y por eso las dos causas se suman a lo largo de una vida de trabajo en audio.",
    src: "Audiología Básica — referencias/ · Moore",
  },
  {
    id: "psi-tts-pts",
    cat: "Audiología", dif: 2,
    q: "Un TTS (desplazamiento temporal del umbral) tras un concierto…",
    opts: [
      "Se recupera en horas, pero repetido lleva a PTS.",
      "Es permanente desde la primera exposición fuerte.",
      "Sólo afecta a los graves, que llevan más energía.",
      "No tiene relación con la exposición a ruido alto.",
    ],
    ans: 0,
    why: "El zumbido y la sensación de oído tapado después de un show son un TTS: se recupera en horas o días. El problema es que <b>la recuperación no es gratis</b> — la exposición repetida va dejando daño acumulado hasta volverse PTS, permanente e irreversible, porque las células ciliadas no se regeneran. El TTS no es un aviso inofensivo: es la señal de que ya estás gastando reserva.",
    src: "Audiología Básica — referencias/ · Moore · ISO 1999",
  },

].map((q) => ({ ...q, area: "psicoacustica" }));
