// COLECCIÓN: Kuttruff, Room Acoustics (referencias/Room Acoustics - Kuttruf.pdf).
//
// Colección atada a un documento y sus secciones (capítulos). Cada ítem lleva
// `seccion` + `cat`; `fuente` se aplica con .map() al final. NO lleva `area`.
// Misma regla de oro: 4 opciones del mismo largo (±5). Validar con check_banco.py.
// Páginas: impresa = pág. PDF − 21 (offset verificado contra el PDF, sep 2026).
// Ver plan_pdf_secciones.md.

export const KUTTRUFF_RA = [

  // ─── Cap. 3: Ondas en la sala ───
  {
    id: "col-ku-schroeder",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 2,
    q: "¿Dónde sitúa Kuttruff la frecuencia de Schroeder?",
    opts: [
      "fs ≈ 2000·√(T/V), con T el RT y V el volumen.",
      "fs ≈ 2000·√(V/T), con V el volumen y T el RT.",
      "fs ≈ c/(2L), con L la dimensión más larga real.",
      "fs ≈ 0,161·V/A, con A el área de absorción.",
    ],
    ans: 0,
    why: "Kuttruff define la frecuencia de Schroeder como fs ≈ 2000·√(T/V) (SI): por encima de ella hay solapamiento fuerte de resonancias (≳3 modos por ancho de banda) y vale la acústica estadística; por debajo, el campo es modal y depende de la posición. Es el límite entre el tratamiento de onda y el estadístico.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.44), p. 67",
  },
  {
    id: "col-ku-densidad-modal",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "La densidad de frecuencias propias dN/df de una sala crece con…",
    opts: [
      "f², como 4πV·f²/c³ (término de volumen).",
      "f, de forma lineal con la frecuencia dada.",
      "f³, igual que el total de modos bajo f real.",
      "1/f, decrece al subir en frecuencia siempre.",
    ],
    ans: 0,
    why: "El número de modos por debajo de f va como (4π/3)·V·(f/c)³, así que su derivada (la densidad modal) crece con f². Por eso los modos se agolpan cada vez más rápido y a partir de la frecuencia de Schroeder ya no tiene sentido contarlos de a uno. Es la base del cruce entre régimen modal y difuso.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.27), p. 59",
  },
  {
    id: "col-ku-T-delta",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "Kuttruff escribe el RT como T = 6,91/δ, donde δ es…",
    opts: [
      "La constante de amortiguamiento del decaimiento.",
      "El coeficiente de absorción medio de la sala.",
      "La densidad de energía en estado estacionario.",
      "La frecuencia propia más baja del recinto dado.",
    ],
    ans: 0,
    why: "La energía decae como e^(−2δt). Una caída de 60 dB equivale a e^(−2δT) = 10⁻⁶, o sea 2δT = 6·ln(10) = 13,8, de donde T = 6,91/δ. El δ (constante de amortiguamiento) resume las pérdidas por absorción, y liga el decaimiento temporal con el ancho de banda de cada modo (Q). Es la forma «de onda» del tiempo de reverberación.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.44), p. 67",
  },

  // ─── Cap. 4: Acústica geométrica ───
  {
    id: "col-ku-lambert",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 2,
    q: "La ley del coseno de Lambert describe una reflexión…",
    opts: [
      "Difusa: la intensidad radiada varía con el cos θ.",
      "Especular: la salida iguala el ángulo de entrada.",
      "Nula: la superficie absorbe toda la energía dada.",
      "Focalizada: concentra la energía en un punto real.",
    ],
    ans: 0,
    why: "En una reflexión difusa ideal, la energía se re-irradia según la ley de Lambert: la intensidad en una dirección va con el coseno del ángulo respecto de la normal, independientemente de por dónde llegó el sonido. Es el modelo opuesto a la reflexión especular (ángulo igual al de incidencia) y el que usan los métodos de radiosidad acústica.",
    src: "Kuttruff, Room Acoustics, cap. 4 (Ec. 4.24), p. 96",
  },
  {
    id: "col-ku-imagenes",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 3,
    q: "El método de fuentes imagen es exacto y ordenado para…",
    opts: [
      "Recintos rectangulares; formas irregulares lo enredan.",
      "Cualquier forma de sala, sin límite de orden alguno.",
      "Sólo el campo difuso por encima de la f de Schroeder.",
      "Salas con paredes totalmente absorbentes únicamente.",
    ],
    ans: 0,
    why: "En una caja rectangular las imágenes forman una retícula regular que llena el espacio sin huecos ni solapamientos. En salas de forma irregular las imágenes se multiplican de manera desordenada y sus «espacios imagen» se solapan, así que el método pierde exactitud y se vuelve impracticable a orden alto: ahí entran los métodos híbridos con rayos.",
    src: "Kuttruff, Room Acoustics, cap. 4, p. 84",
  },

  // ─── Cap. 4: Acústica geométrica (completar el capítulo, 20 preguntas) ───
  {
    id: "col-ku4-validez",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 2,
    q: "La acústica geométrica es válida cuando…",
    opts: [
      "la longitud de onda es chica frente a las dimensiones.",
      "la longitud de onda es grande frente a las dimensiones.",
      "la sala está por debajo de la frecuencia de Schroeder.",
      "las paredes son perfectamente rígidas y sin absorción.",
    ],
    ans: 0,
    why: "La acústica geométrica es el límite de longitud de onda tendiendo a cero (frecuencias altas): vale cuando las dimensiones de la sala y de sus detalles son grandes frente a la longitud de onda. Reemplaza ondas por rayos rectos, desprecia difracción e interferencia y suma energías (no amplitudes), lo que es lícito si las componentes son incoherentes.",
    src: "Kuttruff, Room Acoustics, cap. 4, p. 81",
  },
  {
    id: "col-ku4-especular",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 2,
    q: "La ley de reflexión especular de un rayo se escribe u' = u − 2(u·n)·n, donde…",
    opts: [
      "n es la normal a la pared en el punto de incidencia.",
      "n es la dirección del rayo incidente ya normalizada.",
      "n es el coeficiente de absorción de la pared dada.",
      "n es el número de reflexiones que sufre el rayo real.",
    ],
    ans: 0,
    why: "En la reflexión especular el rayo queda en el plano del rayo incidente y la normal, y el ángulo de incidencia iguala al de reflexión. En forma vectorial u' = u − 2(u·n)·n, con u y u' los versores de rayo incidente y reflejado y n el versor normal a la pared en el punto de choque. Es la misma ley que en óptica.",
    src: "Kuttruff, Room Acoustics, cap. 4 (Ec. 4.1), p. 82",
  },
  {
    id: "col-ku4-esquina",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 3,
    q: "Un rayo que sufre doble reflexión en una esquina recta de dos paredes…",
    opts: [
      "vuelve en la misma dirección de la que vino siempre.",
      "sale perpendicular a la dirección con que había llegado.",
      "se pierde: la esquina absorbe toda su energía siempre.",
      "duplica su intensidad al concentrarse en el vértice.",
    ],
    ans: 0,
    why: "Una esquina recta formada por dos paredes perpendiculares actúa como retrorreflector: el rayo, tras la doble reflexión, vuelve exactamente en la dirección de la que vino, sea cual sea el ángulo de llegada. Si el ángulo de la esquina se aparta un δ del recto, el rayo saldrá desviado 2δ. Lo mismo ocurre en 3D con un rincón de tres planos.",
    src: "Kuttruff, Room Acoustics, cap. 4, p. 82",
  },
  {
    id: "col-ku4-imagen-exacta",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 3,
    q: "El método de fuentes imagen es rigurosamente exacto solo si la pared tiene…",
    opts: [
      "impedancia de reflexión total, con factor R igual a ±1.",
      "un coeficiente de absorción medio para campo difuso.",
      "una impedancia que crece de forma lineal con la f real.",
      "una superficie curva de radio grande frente a la λ dada.",
    ],
    ans: 0,
    why: "El concepto de fuente imagen es exacto solo si la pared refleja totalmente (factor de reflexión ±1). En los demás casos hay error, porque el factor de reflexión y el coeficiente de absorción se definen para ondas planas, mientras que las de la fuente real y sus imágenes son esféricas. El error es tolerable si la fuente está al menos a unas pocas longitudes de onda de la pared.",
    src: "Kuttruff, Room Acoustics, cap. 4, p. 83",
  },
  {
    id: "col-ku4-echograma",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 2,
    q: "En acústica geométrica, la respuesta al impulso de la sala (echograma) es…",
    opts: [
      "una serie de reflexiones retardadas, cada una con su nivel.",
      "una senoide amortiguada única con un tiempo de caída fijo.",
      "un espectro continuo y liso, sin estructura temporal alguna.",
      "una sola reflexión especular en la pared más cercana dada.",
    ],
    ans: 0,
    why: "Sumando la fuente y todas sus imágenes, la respuesta al impulso es g(t) = Σ Aₙ·δ(t−tₙ): una sucesión de reflexiones, cada una con su retardo tₙ (por el camino recorrido) y su energía Aₙ. Representada como rayas verticales sobre el eje de tiempo, es el echograma o diagrama de reflexiones, base del análisis de sonido directo, primeras reflexiones y reverberación.",
    src: "Kuttruff, Room Acoustics, cap. 4 (Ec. 4.5), p. 86",
  },
  {
    id: "col-ku4-reflexion-deforma",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 3,
    q: "En la realidad, un impulso de Dirac al reflejarse en una pared…",
    opts: [
      "se deforma; su transformada es el factor de reflexión R.",
      "se refleja idéntico, sin ningún cambio de forma real.",
      "se convierte siempre en un ruido blanco de banda ancha.",
      "se retrasa pero conserva su forma exacta de impulso.",
    ],
    ans: 0,
    why: "Un impulso ideal no se refleja idéntico: cada reflexión lo transforma en una señal distinta r(t), la «respuesta de reflexión» de la superficie, cuya transformada de Fourier es el factor de reflexión complejo R (dependiente de la frecuencia). Por eso el echograma con δ perfectos es una idealización; las reflexiones reales están coloreadas por la respuesta de cada pared.",
    src: "Kuttruff, Room Acoustics, cap. 4, p. 86",
  },
  {
    id: "col-ku4-tasa-reflexiones",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 3,
    q: "La tasa media de reflexiones que llegan a un punto crece con el tiempo como…",
    opts: [
      "t²: vale dNr/dt = 4πc³t²/V y por eso se densifican.",
      "t: crece de forma lineal con el tiempo transcurrido.",
      "1/t: se hacen cada vez más raras al avanzar el tiempo.",
      "constante: llegan siempre al mismo ritmo en el tiempo.",
    ],
    ans: 0,
    why: "Usando el sistema de salas imagen, las reflexiones que llegan entre t y t+dt vienen de imágenes en una cáscara esférica de radio ct, de volumen 4πc²t²·c·dt. Dividiendo por el volumen de la sala sale dNr/dt = 4πc³t²/V: la densidad de reflexiones crece con t². Tiene la misma forma que la densidad de modos (Ec. 3.26), y vale también para forma arbitraria.",
    src: "Kuttruff, Room Acoustics, cap. 4 (Ec. 4.6), p. 87",
  },
  {
    id: "col-ku4-fourier-red",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 3,
    q: "El patrón de fuentes imagen y la red de eigenfrecuencias están, entre sí…",
    opts: [
      "como transformadas de Fourier espaciales, una de la otra.",
      "totalmente desligados, sin ninguna relación formal real.",
      "en relación lineal directa, uno proporcional al otro.",
      "idénticos punto a punto, son exactamente el mismo objeto.",
    ],
    ans: 0,
    why: "Kuttruff señala que la densidad de reflexiones (Ec. 4.6) y la densidad de eigenfrecuencias (Ec. 3.26) tienen la misma forma matemática. No es casualidad: el patrón de fuentes imagen y la red de autovalores en el espacio k son transformadas de Fourier espaciales una de la otra, como la red directa y la recíproca en cristalografía. Es el puente onda–rayo hecho explícito.",
    src: "Kuttruff, Room Acoustics, cap. 4, p. 87",
  },
  {
    id: "col-ku4-decae-propio",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 3,
    q: "En una caja rectangular de paredes lisas, cada rayo decae a un ritmo propio y…",
    opts: [
      "la curva de decaimiento sale curvada, no una recta.",
      "la curva de decaimiento sale siempre una recta perfecta.",
      "todos los rayos decaen exactamente al mismo ritmo dado.",
      "el decaimiento no depende de la dirección del rayo real.",
    ],
    ans: 0,
    why: "El número de cruces de pared por segundo depende del ángulo del rayo: n(θₓ,θ_y,θ_z), con cos²θₓ+cos²θ_y+cos²θ_z=1. Así cada rayo decae a su propio ritmo, y la curva de decaimiento resulta curvada (no recta), tal como se vio en la Sección 3.8. Solo si algo mezcla las direcciones (forma irregular, paredes difusoras) se llega a un decaimiento común y recto.",
    src: "Kuttruff, Room Acoustics, cap. 4, p. 88",
  },
  {
    id: "col-ku4-n-reflexiones",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 3,
    q: "En campo difuso, el número medio de reflexiones por segundo de un rayo vale…",
    opts: [
      "n = cS/4V: crece con el área y baja con el volumen.",
      "n = 4V/cS: el inverso, sube con el volumen dado.",
      "n = cV/4S: proporcional al volumen sobre el área.",
      "n = c/2L, con L la dimensión más larga de la sala.",
    ],
    ans: 0,
    why: "Promediando los cruces de pared sobre todas las direcciones, el número medio de reflexiones por segundo es n = cS/4V, con S el área total de las paredes y V el volumen. Es el inverso del tiempo entre reflexiones; dividiendo el camino por n se obtiene el camino libre medio 4V/S. Es la bisagra entre la visión de rayos y la fórmula de reverberación.",
    src: "Kuttruff, Room Acoustics, cap. 4 (Ec. 4.9), p. 89",
  },
  {
    id: "col-ku4-T-geometrico",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 3,
    q: "Del balance geométrico de energía, la reverberación resulta T = 0,161·V/(…):",
    opts: [
      "4mV − S·ln(1−ᾱ): con el término 4mV del aire dado.",
      "S·ᾱ solamente: sin término de aire ni logaritmo real.",
      "V·ᾱ: proporcional al volumen por la absorción media.",
      "4mV + S·ᾱ²: con la absorción media puesta al cuadrado.",
    ],
    ans: 0,
    why: "Contando cruces de pared y absorción por reflexión, la energía decae como exp[−ct(4mV−S·ln(1−ᾱ))/4V], de donde T = 0,161·V/(4mV − S·ln(1−ᾱ)). El término 4mV suma la atenuación del aire. Es la fórmula tipo Eyring, deducida acá por pura geometría de rayos; en el cap. 5 se llega a lo mismo por balance de energía.",
    src: "Kuttruff, Room Acoustics, cap. 4 (Ec. 4.12), p. 89",
  },
  {
    id: "col-ku4-flutter",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 2,
    q: "El «flutter echo» (eco flotante) aparece típicamente…",
    opts: [
      "entre dos paredes paralelas y rígidas, yendo y viniendo.",
      "en salas esféricas con la absorción muy bien repartida.",
      "cuando todas las paredes absorben por igual el sonido.",
      "solo por debajo de la frecuencia de Schroeder de la sala.",
    ],
    ans: 0,
    why: "El eco flotante son reflexiones periódicas del sonido yendo y viniendo entre dos paredes paralelas rígidas. Con períodos de pocos milisegundos se percibe como «coloración» del sonido; con 30 a 100 ms, como repeticiones audibles. Es frecuente en pasillos o salas alargadas con las paredes de los extremos rígidas y el resto absorbente.",
    src: "Kuttruff, Room Acoustics, cap. 4, p. 90",
  },
  {
    id: "col-ku4-difuso",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 2,
    q: "Un campo sonoro se llama «difuso» (isótropo) cuando…",
    opts: [
      "la distribución direccional no depende de la dirección.",
      "la energía llega toda desde una única dirección fija.",
      "no hay ninguna reflexión, solo el sonido directo puro.",
      "la presión es la misma en todos los puntos de la sala.",
    ],
    ans: 0,
    why: "El campo es difuso o isótropo cuando la distribución direccional I(θ,φ) no depende de los ángulos: el sonido llega por igual desde todas las direcciones. Es, en cierto sentido, el opuesto de la onda plana (una sola dirección). El campo real de una sala nunca es perfectamente difuso, pero se parece más a un campo difuso que a una onda plana, y por eso es un modelo tan útil.",
    src: "Kuttruff, Room Acoustics, cap. 4, p. 91",
  },
  {
    id: "col-ku4-absorcion-no-uniforme",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 3,
    q: "Si la absorción se concentra en una sola pared (resto rígido), el decaimiento…",
    opts: [
      "deja de ser exponencial: la energía cae como 1/t real.",
      "sigue siendo exponencial, con el mismo tiempo de siempre.",
      "se vuelve una recta perfecta en la escala lineal de t.",
      "no cambia respecto del caso de absorción bien repartida.",
    ],
    ans: 0,
    why: "Kuttruff analiza una caja con una pared totalmente absorbente y el resto rígido: el campo es cualquier cosa menos isótropo. Integrando sobre las direcciones válidas, la energía que decae no sigue una ley exponencial sino que cae proporcional a 1/t. Es un recordatorio de que las fórmulas de reverberación suponen campo difuso, que la absorción muy despareja rompe.",
    src: "Kuttruff, Room Acoustics, cap. 4 (Ec. 4.16), p. 92",
  },
  {
    id: "col-ku4-concava",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 3,
    q: "Una pared cóncava (espejo esférico) sigue 1/a + 1/b = 2/R y tiende a…",
    opts: [
      "concentrar el sonido, algo por lo general perjudicial.",
      "difundir el sonido de manera siempre uniforme y buena.",
      "absorber toda la energía que incide sobre ella misma.",
      "no afectar en nada la distribución del sonido real.",
    ],
    ans: 0,
    why: "Una superficie cóncava se comporta como espejo cóncavo: relaciona distancias por 1/a + 1/b = 2/R (R el radio de curvatura). Tiende a concentrar la energía reflejada en ciertas zonas, algo generalmente perjudicial (foco, distribución despareja). La regla práctica: si fuente y receptor están fuera del círculo de radio R, esos efectos indeseables no se esperan.",
    src: "Kuttruff, Room Acoustics, cap. 4 (Ec. 4.17), p. 93",
  },
  {
    id: "col-ku4-whispering",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 2,
    q: "Una «galería de susurros» funciona porque los rayos rasantes…",
    opts: [
      "quedan guiados a lo largo de la pared curva y lisa.",
      "se concentran todos en el centro geométrico del salón.",
      "se absorben en la pared y no llegan lejos nunca jamás.",
      "rebotan una sola vez y salen hacia el techo del salón.",
    ],
    ans: 0,
    why: "En una sala circular o elíptica, muchos rayos que salen de la boca del hablante golpean la pared con incidencia rasante y se reflejan una y otra vez, quedando confinados en una banda angosta: la pared conduce el sonido por su perímetro. Por eso un oyente pegado a la pared, aunque lejano, escucha con claridad hasta un susurro. El ejemplo clásico es la cúpula de St. Paul en Londres.",
    src: "Kuttruff, Room Acoustics, cap. 4, p. 95",
  },
  {
    id: "col-ku4-elipse",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 2,
    q: "En una sala de planta elíptica, una fuente en un foco hace que los rayos…",
    opts: [
      "se junten todos en el otro foco de la elipse dada.",
      "se repartan de forma pareja por toda la sala real.",
      "vuelvan exactamente al mismo foco de donde salieron.",
      "salgan todos paralelos hacia una sola pared lateral.",
    ],
    ans: 0,
    why: "La elipse tiene dos focos: si la fuente está en uno, todos los rayos que emite se colectan en el otro. Por eso las salas de planta elíptica (o circular, caso límite) sufren una distribución de sonido muy despareja, aun cuando ni la fuente ni el oyente estén en un foco geométrico. Es una de las geometrías más problemáticas en acústica de salas.",
    src: "Kuttruff, Room Acoustics, cap. 4, p. 95",
  },
  {
    id: "col-ku4-radio-curvatura",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 3,
    q: "La ley de reflexión especular deja de aplicarse a una pared curva cuando…",
    opts: [
      "su radio de curvatura no es grande frente a la λ dada.",
      "su radio de curvatura es mucho mayor que la λ del sonido.",
      "la sala está por encima de la frecuencia de Schroeder.",
      "la pared es plana y del todo lisa en toda su área real.",
    ],
    ans: 0,
    why: "Formalmente la ley especular vale para superficies curvas (cada trozo se aproxima por planos), pero no hay que aplicarla si el radio de curvatura no es muy grande frente a la longitud de onda. Cuando el radio es comparable o menor que λ, la superficie dispersa la onda en vez de reflejarla especularmente. Es el límite de validez de todo el enfoque geométrico.",
    src: "Kuttruff, Room Acoustics, cap. 4, p. 92",
  },
  {
    id: "col-ku4-radiosidad",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 3,
    q: "La «integral de radiosidad» describe el campo cuando las paredes reflejan…",
    opts: [
      "de forma difusa (Lambert), como una ecuación integral.",
      "de forma especular pura, con el método de las imágenes.",
      "toda la energía, sin ninguna absorción en las paredes.",
      "solo por debajo de la frecuencia de Schroeder de la sala.",
    ],
    ans: 0,
    why: "Si toda la frontera refleja de forma completamente difusa (ley de Lambert), el campo se describe con una ecuación integral para la irradiancia B: la integral de radiosidad. Cada elemento de pared actúa como fuente secundaria y la distancia del 1/r² se mide desde ese elemento (no desde la fuente original, como en la reflexión especular). Es la base del método de radiosidad acústica.",
    src: "Kuttruff, Room Acoustics, cap. 4 (Ec. 4.26), p. 97",
  },
  {
    id: "col-ku4-difusion",
    seccion: "Cap. 4: Acústica geométrica", cat: "Cap. 4: Acústica geométrica", dif: 3,
    q: "La ecuación de difusión acústica trata el sonido como partículas y usa D =…",
    opts: [
      "c·ℓ/3, con ℓ = 4V/S el camino libre medio dado.",
      "c·S/4V, la tasa media de reflexiones por segundo.",
      "c²·T, el cuadrado de la velocidad por el RT.",
      "V/S, la simple razón entre volumen y superficie.",
    ],
    ans: 0,
    why: "Tratando el campo como un gas de partículas de sonido en movimiento browniano, la densidad de energía obedece una ecuación de difusión (la misma que la del calor), con constante de difusión D = c·ℓ/3, donde ℓ = 4V/S es el camino libre medio. Para el decaimiento basta el autovalor más bajo, así que necesita muchas menos incógnitas que resolver la ecuación de onda. Vale solo si el campo es casi difuso.",
    src: "Kuttruff, Room Acoustics, cap. 4 (Ec. 4.38), p. 101",
  },

  // ─── Cap. 5: Reverberación ───
  {
    id: "col-ku-mfp",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 2,
    q: "El camino libre medio de una sala difusa vale…",
    opts: [
      "4V/S: distancia media entre dos reflexiones.",
      "V/S: la razón simple entre volumen y área.",
      "S/4V: el inverso del volumen sobre el área.",
      "c·T: la distancia recorrida en un RT dado.",
    ],
    ans: 0,
    why: "En campo difuso, un rayo recorre en promedio 4V/S entre rebote y rebote. Dividiendo por c da el tiempo medio entre reflexiones, y contando cuántas hacen falta para caer 60 dB se llega a la fórmula de reverberación. Es la bisagra entre la visión de rayos y la acústica estadística, y de donde sale la constante de Sabine.",
    src: "Kuttruff, Room Acoustics, cap. 5, p. 110",
  },
  {
    id: "col-ku-eyring",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "La fórmula de Eyring, frente a la de Sabine, usa en el denominador…",
    opts: [
      "−ln(1−ᾱ) en lugar de ᾱ: mejor con ᾱ alto.",
      "ᾱ² en lugar de ᾱ: peor con absorción baja.",
      "el volumen V en lugar del área S del recinto.",
      "la superficie S sola, sin el coeficiente ᾱ.",
    ],
    ans: 0,
    why: "Eyring reemplaza S·ᾱ por −S·ln(1−ᾱ). Como −ln(1−ᾱ) ≈ ᾱ para ᾱ chico, coincide con Sabine en salas poco absorbentes; con ᾱ alto, Sabine sobrestima el RT (supone absorción continua, cuando cada reflexión se come una fracción grande). En el límite ᾱ = 1, Eyring da RT cero (correcto) y Sabine un valor finito absurdo.",
    src: "Kuttruff, Room Acoustics, cap. 5 (Ec. 5.24), p. 113",
  },

  // ─── Cap. 5: Reverberación (completar el capítulo, 20 preguntas) ───
  {
    id: "col-ku5-densidad-energia",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "En un campo difuso, la densidad de energía se relaciona con la intensidad por…",
    opts: [
      "w = 4πI/c: se integra la intensidad en todo el espacio.",
      "w = I/c: igual que en una onda plana progresiva simple.",
      "w = I·c: el producto de la intensidad por la velocidad.",
      "w = c/4πI: el inverso de la intensidad por la velocidad.",
    ],
    ans: 0,
    why: "A un haz de rayos casi paralelos dentro de un ángulo sólido dΩ le corresponde dw = I·dΩ/c. Como en un campo difuso I no depende de la dirección, integrar sobre todo el espacio equivale a multiplicar por 4π: w = 4πI/c. Se compara con w = I/c de una onda plana progresiva, donde toda la energía viaja en una sola dirección.",
    src: "Kuttruff, Room Acoustics, cap. 5 (Ec. 5.2), p. 104",
  },
  {
    id: "col-ku5-densidad-constante",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 2,
    q: "En un campo difuso estacionario, la densidad de energía es…",
    opts: [
      "la misma en todos los puntos del recinto considerado.",
      "máxima en el centro y menor cerca de las paredes.",
      "distinta en cada punto según su distancia a la fuente.",
      "cero salvo justo sobre la superficie de las paredes.",
    ],
    ans: 0,
    why: "Kuttruff muestra que en un campo difuso la densidad de energía es constante en todo el recinto: dos puntos cualesquiera comparten un rayo, y como la energía no cambia a lo largo de un rayo, sus distribuciones direccionales deben tener el mismo tamaño. Ojo: la recíproca no vale, puede haber densidad constante con distribución direccional no uniforme.",
    src: "Kuttruff, Room Acoustics, cap. 5, p. 104",
  },
  {
    id: "col-ku5-irradiancia",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "En campo difuso, la energía que incide por segundo y por área sobre una pared es…",
    opts: [
      "B = c·w/4: un cuarto de la densidad por la velocidad.",
      "B = c·w: la densidad de energía por la velocidad entera.",
      "B = 4·c·w: cuatro veces la densidad por la velocidad.",
      "B = w/4c: la densidad sobre cuatro veces la velocidad.",
    ],
    ans: 0,
    why: "La irradiancia (energía incidente por unidad de tiempo y área sobre una pared) en campo difuso es B = c·w/4. El factor 1/4 sale de promediar el coseno del ángulo de incidencia sobre el hemisferio. Se contrasta con w = I/c de la onda plana: el campo difuso, al llegar desde todas las direcciones, entrega a la pared un cuarto de c·w.",
    src: "Kuttruff, Room Acoustics, cap. 5 (Ec. 5.3), p. 105",
  },
  {
    id: "col-ku5-estacionario",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "Con potencia P constante, la densidad de energía estacionaria de la sala vale…",
    opts: [
      "w = 4P/(c·A), con A el área de absorción equivalente.",
      "w = P·A/(4c), proporcional al área de absorción.",
      "w = c·A/(4P), el inverso de la potencia inyectada.",
      "w = P/(c·V), la potencia sobre el volumen de la sala.",
    ],
    ans: 0,
    why: "El balance de energía P = V·dw/dt + c·A·w/4 iguala la potencia inyectada con el aumento de energía más lo absorbido por la frontera (A = área de absorción equivalente). En régimen estacionario dw/dt = 0, así que w = 4P/(c·A). Es la base del campo reverberante y de la medición de potencia acústica en cámara reverberante.",
    src: "Kuttruff, Room Acoustics, cap. 5 (Ec. 5.5), p. 105",
  },
  {
    id: "col-ku5-sabine-falla",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 2,
    q: "La fórmula de Sabine T = 0,161·V/A falla con absorción alta porque…",
    opts: [
      "predice un RT finito aun con α = 1, lo cual es absurdo.",
      "predice RT cero aun con paredes casi del todo rígidas.",
      "solo vale por encima de la frecuencia de Schroeder real.",
      "supone que el aire no absorbe nada de energía sonora.",
    ],
    ans: 0,
    why: "Sabine, T = 0,161·V/A, es la fórmula más conocida de la acústica de salas, pero falla con absorción alta: para α = 1 predice un RT finito, cuando una sala sin paredes reflejantes no puede reverberar. La causa es que durante un decaimiento rápido la sala no está en el estado estacionario que la derivación supone. Para salas «muertas» se usan Eyring o fórmulas más exactas.",
    src: "Kuttruff, Room Acoustics, cap. 5 (Ec. 5.8), p. 105",
  },
  {
    id: "col-ku5-formas-difusas",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 2,
    q: "Para favorecer un campo difuso, conviene que la sala tenga…",
    opts: [
      "forma irregular, o paredes que dispersen bien el sonido.",
      "paredes cóncavas que concentren la energía reflejada.",
      "superficies muy lisas y perfectamente paralelas entre sí.",
      "toda su absorción concentrada en una única pared dada.",
    ],
    ans: 0,
    why: "Un campo difuso se establece cuando las direcciones de propagación se mezclan sin cesar. Ayudan las formas irregulares y sobre todo las paredes acústicamente «rugosas» (difusoras), que dispersan el sonido en muchas direcciones. Lo contrario (paredes cóncavas que concentran, superficies lisas paralelas) va contra la difusión. Las paredes difusoras solas no bastan: también importa que la absorción sea baja y pareja.",
    src: "Kuttruff, Room Acoustics, cap. 5, p. 106",
  },
  {
    id: "col-ku5-irreversible",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "La conversión de energía especular en energía difusa, reflexión tras reflexión…",
    opts: [
      "es irreversible: tras pocas reflexiones casi todo es difuso.",
      "es reversible: la energía difusa vuelve a ser rayo dirigido.",
      "no ocurre nunca en salas de paredes lisas y bien rígidas.",
      "reduce la energía total, sumando pérdidas en cada rebote.",
    ],
    ans: 0,
    why: "Pasar energía «especular» a «difusa» (no especular) es un proceso irreversible: nunca ocurre que el sonido difuso se reconvierta en un rayo con dirección bien definida. Separando la reflexión en una fracción difusa s·(1−α) y una especular (1−s)·(1−α), la parte especular decae como [(1−s)(1−α)]ⁿ: tras unas pocas reflexiones casi toda la energía se volvió difusa. s es el coeficiente de dispersión (scattering).",
    src: "Kuttruff, Room Acoustics, cap. 5, p. 106",
  },
  {
    id: "col-ku5-volumen-difusores",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 2,
    q: "Los «difusores de volumen» (cuerpos colgados al azar en la sala) sirven para…",
    opts: [
      "aumentar la difusión dispersando los rayos que pasan.",
      "absorber la energía sonora en el interior de la sala.",
      "concentrar el sonido en el centro geométrico del recinto.",
      "bajar la frecuencia de Schroeder de la sala directamente.",
    ],
    ans: 0,
    why: "Colgar cuerpos rígidos al azar en el volumen dispersa las partículas de sonido en todas las direcciones y aumenta la difusión, incluso aplicándolo solo a partes de la sala. Es poco práctico en salas de espectáculo (ocupan espacio) pero muy usado en cámaras reverberantes de medición. Su eficiencia depende de la razón entre el camino libre entre difusores rs = 1/(nsQs) y el camino libre de pared 4V/S.",
    src: "Kuttruff, Room Acoustics, cap. 5, p. 107",
  },
  {
    id: "col-ku5-tiempo-ensemble",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "En un campo difuso, el promedio temporal de una partícula y el de ensemble…",
    opts: [
      "coinciden: da igual promediar en tiempo o entre partículas.",
      "difieren por un factor igual a la absorción media dada.",
      "solo coinciden si la sala es un cubo perfecto y rígido.",
      "no tienen ninguna relación entre sí, en ningún caso real.",
    ],
    ans: 0,
    why: "En un campo difuso las partículas cambian de dirección y de rol una y otra vez hasta perder su individualidad. Por eso deja de importar la distinción entre promediar en el tiempo el destino de una partícula o promediar en un instante sobre muchas: promedio temporal = promedio de ensemble. Esta equivalencia es lo que hace tan simple deducir n = cS/4V y el camino libre medio 4V/S.",
    src: "Kuttruff, Room Acoustics, cap. 5, p. 109",
  },
  {
    id: "col-ku5-tasa-reflexiones",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 2,
    q: "En campo difuso, la tasa media de reflexiones de una partícula de sonido es…",
    opts: [
      "n = c·S/4V, válida para salas de cualquier forma.",
      "n = 4V/(c·S), el inverso, que crece con el volumen.",
      "n = c/2L, fijada solo por la dimensión más larga.",
      "n = c·V/4S, proporcional al volumen sobre el área.",
    ],
    ans: 0,
    why: "Con un solo sonido-partícula de energía e₀, su aporte a la densidad es e₀/V y el que lleva a la pared por segundo es n·e₀/S. Igualando con B = c·w/4 sale n = c·S/4V, ahora deducida para forma arbitraria (no solo la caja rectangular del cap. 4). Su inverso por c da el camino libre medio 4V/S.",
    src: "Kuttruff, Room Acoustics, cap. 5 (Ec. 5.11), p. 109",
  },
  {
    id: "col-ku5-media-ponderada",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "Con paredes de distinta absorción, el decaimiento se rige por…",
    opts: [
      "la media de α pesada por áreas: ᾱ = (Σ Sᵢαᵢ)/S.",
      "el valor máximo de α entre todas las paredes reales.",
      "el valor mínimo de α entre todas las paredes reales.",
      "la suma directa de las α sin pesar por las áreas.",
    ],
    ans: 0,
    why: "Siguiendo una partícula por N reflexiones repartidas según las áreas (distribución binomial), la energía media queda E = E₀·(1−ᾱ)ᴺ con ᾱ = (S₁α₁+S₂α₂+…)/S: la media aritmética de los coeficientes pesada por las áreas. Ese ᾱ es el que entra en Eyring, A = S·ᾱ es el área de absorción equivalente, y es la forma correcta de combinar materiales distintos.",
    src: "Kuttruff, Room Acoustics, cap. 5 (Ec. 5.20), p. 112",
  },
  {
    id: "col-ku5-millington",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "La fórmula de Millington–Sette (que promedia −ln(1−α)) tiene el problema de que…",
    opts: [
      "una pared con α = 1 anula el RT, por chica que sea.",
      "sobrestima el RT en salas de absorción muy alta.",
      "coincide exactamente con Sabine en todos los casos.",
      "ignora por completo las áreas de cada tipo de pared.",
    ],
    ans: 0,
    why: "Millington–Sette promedia el «exponente de absorción» −ln(1−α) en vez de α. Eso tiene una consecuencia extraña: si una porción de pared tiene α = 1, su −ln(1−α) es infinito, y el RT calculado daría cero por más chica que sea esa porción. Es un resultado a todas luces irrazonable, que muestra los límites de promediar el exponente en vez del coeficiente.",
    src: "Kuttruff, Room Acoustics, cap. 5 (Ec. 5.27), p. 113",
  },
  {
    id: "col-ku5-varianza-caminos",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "Al tener en cuenta que los caminos libres no son todos iguales, aparece…",
    opts: [
      "la varianza relativa γ² de la distribución de caminos.",
      "un término que solo depende del volumen de la sala.",
      "una corrección que anula por completo la absorción.",
      "la frecuencia de Schroeder como límite del cálculo.",
    ],
    ans: 0,
    why: "Eyring supone implícitamente que en un tiempo t hay siempre N = n·t reflexiones. En rigor N es una variable aleatoria, y al promediar exp(−N·a) aparece la varianza relativa γ² = (⟨l²⟩−⟨l⟩²)/⟨l⟩² de la distribución de caminos libres. El exponente de absorción corregido es a' = −ln(1−ᾱ)/(1 + (γ²/2)·ln(1−ᾱ)).",
    src: "Kuttruff, Room Acoustics, cap. 5 (Ec. 5.34), p. 115",
  },
  {
    id: "col-ku5-gamma-valores",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "La varianza relativa γ² de los caminos libres vale, para formas típicas…",
    opts: [
      "cerca de 0,4 en salas rectangulares; 1/8 en una esfera.",
      "exactamente cero en cualquier sala tridimensional real.",
      "cerca de 1 en todas las salas, sin importar la forma.",
      "siempre mayor a 2 salvo en el cubo perfecto rígido.",
    ],
    ans: 0,
    why: "La varianza relativa γ² depende de la forma. Para una esfera vale 1/8; para la mayoría de las salas rectangulares ronda 0,4 (Tabla 5.1, por trazado de rayos), valor extensible a formas no muy alejadas del cubo. Si γ² = 0 (recinto 1D, todos los caminos iguales) se recupera Eyring exacto. Es el parámetro con que la forma de la sala entra en la fórmula de reverberación.",
    src: "Kuttruff, Room Acoustics, cap. 5, p. 116",
  },
  {
    id: "col-ku5-rt-mayor-eyring",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "Cuando la varianza de caminos γ² es mayor que cero, el RT resulta…",
    opts: [
      "más largo que el que predice la fórmula de Eyring.",
      "más corto que el que predice la fórmula de Eyring.",
      "idéntico al de Eyring, sin ninguna diferencia real.",
      "independiente de la absorción media de las paredes.",
    ],
    ans: 0,
    why: "Con γ² > 0 el exponente de absorción corregido a' es menor que −ln(1−ᾱ), así que el tiempo de reverberación resulta más largo que el de Eyring. Eyring es estrictamente válido solo para recintos unidimensionales (γ² = 0, todos los caminos iguales). En salas reales, la dispersión de caminos libres alarga algo la reverberación respecto de la predicción de Eyring.",
    src: "Kuttruff, Room Acoustics, cap. 5, p. 115",
  },
  {
    id: "col-ku5-mtf",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "La función de transferencia de modulación (MTF) de una sala describe cómo…",
    opts: [
      "la reverberación suaviza y retrasa las fluctuaciones de nivel.",
      "las paredes amplifican las variaciones rápidas de potencia.",
      "la sala cambia la frecuencia del tono emitido por la fuente.",
      "el aire filtra las frecuencias agudas del sonido directo.",
    ],
    ans: 0,
    why: "Si la potencia de la fuente se modula a frecuencia Ω, la densidad de energía responde con m(Ω) = 2δ/(2δ+iΩ), de módulo siempre menor que 1: la reverberación suaviza (aplana) las fluctuaciones de nivel y las retrasa. Esa m(Ω) es la MTF, base del índice STI de inteligibilidad. Depende del decaimiento δ, que en salas reales varía con la frecuencia del sonido.",
    src: "Kuttruff, Room Acoustics, cap. 5 (Ec. 5.40), p. 118",
  },
  {
    id: "col-ku5-distancia-critica",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "La «distancia crítica» rc de una sala es aquella a la que…",
    opts: [
      "el campo directo y el reverberante tienen igual densidad.",
      "el campo directo se anula por completo en el recinto.",
      "empieza a valer la acústica geométrica de rayos rectos.",
      "la sala pasa a estar por encima de su frecuencia fs.",
    ],
    ans: 0,
    why: "El campo directo cae como wd = P/(4πc·r²) y el reverberante es constante, wr = 4P/(c·A). Se igualan a la distancia crítica rc = √(A/16π) ≈ 0,1·√(V/T). Más cerca domina el sonido directo; más lejos, el reverberante. Con una fuente directiva de ganancia g, la distancia crítica crece como √g. Es un parámetro clave para ubicar micrófonos y oyentes.",
    src: "Kuttruff, Room Acoustics, cap. 5 (Ec. 5.44), p. 118",
  },
  {
    id: "col-ku5-campo-directo",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 2,
    q: "El campo directo de una fuente puntual omnidireccional decae con la distancia como…",
    opts: [
      "1/r²: vale wd = P/(4πc·r²) y baja al alejarse de la fuente.",
      "1/r: baja bastante más lento que el campo reverberante.",
      "1/r³: cae mucho más rápido que una onda esférica real.",
      "no decae: es constante en todo el recinto, igual que wr.",
    ],
    ans: 0,
    why: "El campo directo es la onda esférica de la fuente: su densidad de energía cae como 1/r², wd = P/(4πc·r²). El reverberante, en cambio, es constante en toda la sala, wr = 4P/(c·A). La energía total es w = wd + wr = (4P/cA)·(1 + rc²/r²), y ambos se igualan en la distancia crítica rc. Cerca de la fuente manda el directo; lejos, el reverberante.",
    src: "Kuttruff, Room Acoustics, cap. 5 (Ec. 5.43), p. 118",
  },
  {
    id: "col-ku5-difusa-imperfecta",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "Con difusión imperfecta pero paredes de reflexión difusa (Lambert), el decaimiento…",
    opts: [
      "sigue casi recto, con pendiente igual en toda la sala.",
      "se vuelve muy curvado y distinto en cada punto medido.",
      "deja de existir: la sala no llega a reverberar nunca.",
      "depende solo de la posición de la fuente, no de la pared.",
    ],
    ans: 0,
    why: "Resolviendo la integral de radiosidad (Miles) para una caja con reflexión difusa, las curvas de decaimiento resultan esencialmente rectas y con la misma pendiente final en distintas posiciones. O sea, la difusión imperfecta no implica necesariamente decaimiento no exponencial. Lo que sí cambia es el valor de esa pendiente: el RT puede apartarse bastante del de Eyring.",
    src: "Kuttruff, Room Acoustics, cap. 5, p. 121",
  },
  {
    id: "col-ku5-audiencia-eyring",
    seccion: "Cap. 5: Reverberación", cat: "Cap. 5: Reverberación", dif: 3,
    q: "Con la absorción concentrada en el piso (modelo de platea con público), el RT…",
    opts: [
      "sale más corto que el de Eyring, que reparte parejo.",
      "sale más largo que el de Eyring en todos los casos.",
      "coincide con Eyring, porque el piso no cambia nada.",
      "se vuelve independiente de dónde esté la absorción.",
    ],
    ans: 0,
    why: "Cuando el piso absorbe mucho y el resto es rígido (caso típico de auditorio con público), el piso recibe energía desde todo el hemisferio y absorbe más que en campo difuso: el RT resulta más corto que el de Eyring, que supone absorción bien repartida. Es probablemente la razón por la que el RT de una sala terminada suele salir más corto que el proyectado.",
    src: "Kuttruff, Room Acoustics, cap. 5, p. 123",
  },

  // ─── Cap. 6: Absorción ───
  {
    id: "col-ku-poroso",
    seccion: "Cap. 6: Absorción", cat: "Cap. 6: Absorción", dif: 2,
    q: "En Kuttruff, un absorbente poroso disipa energía por…",
    opts: [
      "Fricción viscosa del aire en sus poros internos.",
      "Resonancia masa-resorte de una membrana tensa.",
      "Reflexión en contrafase que cancela la onda real.",
      "Difracción en los bordes de la muestra colocada.",
    ],
    ans: 0,
    why: "El poroso convierte en calor la velocidad de partícula del aire que atraviesa sus poros, por fricción viscosa. Por eso trabaja donde la velocidad es alta (a λ/4 de una pared rígida) y necesita espesor comparable a la longitud de onda para actuar en graves. Es un mecanismo distinto del resonador (masa-resorte), que es de banda angosta.",
    src: "Kuttruff, Room Acoustics, cap. 6, p. 131",
  },
  {
    id: "col-ku-resonador",
    seccion: "Cap. 6: Absorción", cat: "Cap. 6: Absorción", dif: 2,
    q: "La frecuencia de un resonador de Helmholtz depende de…",
    opts: [
      "El volumen de la cavidad y la geometría del cuello.",
      "Sólo del espesor de la placa perforada utilizada.",
      "La resistividad al flujo del relleno poroso dado.",
      "El área total que expone al campo sonoro real.",
    ],
    ans: 0,
    why: "El resonador de Helmholtz es un sistema masa-resorte: la masa es el tapón de aire del cuello y el resorte, el aire de la cavidad, con f₀ = (c/2π)·√(A/(V·L_eff)). Es de banda angosta y muy eficiente en su frecuencia, ideal para un modo puntual en graves. El relleno poroso amortigua y ensancha la banda, a costa del pico de absorción.",
    src: "Kuttruff, Room Acoustics, cap. 6, p. 132",
  },

  // ─── Cap. 3: Ondas en la sala (ampliación, 20 preguntas) ───
  {
    id: "col-ku3-helmholtz",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 2,
    q: "La teoría de ondas parte de la ecuación de Helmholtz, que es…",
    opts: [
      "la ecuación de onda con la parte temporal armónica ya separada.",
      "la ecuación de onda resuelta paso a paso en el tiempo directo.",
      "una aproximación de rayos válida solo con paredes muy lisas.",
      "la ley de reflexión especular aplicada a una pared por vez.",
    ],
    ans: 0,
    why: "Suponiendo una dependencia temporal e^(iωt), la ecuación de onda se reduce a Δp + k²p = 0, con k = ω/c. Es una ecuación estacionaria en el espacio: la incógnita es la distribución de presión a una frecuencia dada. Sobre ella se imponen las condiciones de contorno de las paredes, y ese es el punto de partida de toda la teoría modal de la sala.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.1), p. 52",
  },
  {
    id: "col-ku3-locally-reacting",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "Una pared «de reacción local» se caracteriza porque su impedancia…",
    opts: [
      "no depende del ángulo con que le llega el sonido incidente.",
      "crece de forma lineal con la frecuencia de la onda incidente.",
      "solo queda definida si la pared es perfectamente rígida.",
      "depende de la presión en todos los puntos vecinos a la vez.",
    ],
    ans: 0,
    why: "En una pared de reacción local, la velocidad normal en cada punto depende solo de la presión en ese mismo punto: la impedancia de pared Z (o la específica ζ = Z/ρ₀c) no depende del ángulo de incidencia ni de la distribución espacial de la onda. Esto simplifica la condición de contorno a Z·(∂p/∂n) + iωρ₀p = 0 y es la hipótesis estándar de la teoría modal.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.3), p. 52",
  },
  {
    id: "col-ku3-ortogonalidad",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "Las autofunciones (modos) de una sala forman un conjunto…",
    opts: [
      "ortogonal: su integral de producto en el volumen se anula.",
      "que solo es ortogonal si la sala es un cubo perfecto dado.",
      "siempre real, aun cuando las paredes absorben energía.",
      "finito, con un número de modos fijo por debajo de la sala.",
    ],
    ans: 0,
    why: "Las autofunciones pₙ(r) son mutuamente ortogonales: ∫pₙpₘ dV = 0 para n ≠ m, e igual a una constante Kₙ para n = m. Esta ortogonalidad permite desarrollar la fuente y la solución como series de modos y despejar los coeficientes término a término. Cuando las paredes tienen absorción, autofunciones y autovalores se vuelven complejos, pero la maquinaria modal sigue valiendo.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.5), p. 52",
  },
  {
    id: "col-ku3-degenerados",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 2,
    q: "Se habla de autovalores «degenerados» cuando…",
    opts: [
      "varias autofunciones distintas comparten el mismo autovalor.",
      "un modo queda sin energía por absorción total de la pared.",
      "el autovalor se vuelve complejo por pérdidas en la pared.",
      "dos salas distintas comparten una misma frecuencia propia.",
    ],
    ans: 0,
    why: "Hay degeneración cuando dos o más autofunciones (modos con estructura espacial distinta) pertenecen al mismo autovalor kₙ, o sea a la misma frecuencia propia. El caso típico es la sala cúbica: por simetría, modos como (1,0,0), (0,1,0) y (0,0,1) caen a la misma frecuencia. La degeneración concentra energía en pocas frecuencias, lo que acústicamente es indeseable.",
    src: "Kuttruff, Room Acoustics, cap. 3, p. 52",
  },
  {
    id: "col-ku3-green-reciprocidad",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "La función de Green de la sala es simétrica en r y r₀; esto expresa…",
    opts: [
      "el teorema de reciprocidad entre fuente y receptor.",
      "que la energía se conserva a lo largo de cada rayo.",
      "que el campo es difuso por encima de la frecuencia fs.",
      "la ley de Sabine para el tiempo de reverberación real.",
    ],
    ans: 0,
    why: "La presión producida por una fuente puntual es la función de Green de la sala, simétrica en las coordenadas de fuente r₀ y observación r. Intercambiar fuente y receptor da la misma presión: es el teorema de reciprocidad, muy útil en medición (a veces conviene poner el micrófono donde iría la fuente y viceversa). Vale exactamente, modo a modo, no solo en promedio.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.10), p. 54",
  },
  {
    id: "col-ku3-delta-resonancia",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "En la función de transferencia de la sala, cada término aporta…",
    opts: [
      "una resonancia centrada en su frecuencia propia ωₙ.",
      "una recta de pendiente fija a lo largo del eje real.",
      "un cero exacto de presión en su frecuencia propia ωₙ.",
      "un retardo puro sin ningún cambio en la amplitud dada.",
    ],
    ans: 0,
    why: "Al escribir kₙ = ωₙ/c + iδₙ/c, cada término de la serie tiene un denominador que se hace mínimo cuando la frecuencia de excitación se acerca a ωₙ: la amplitud llega a un máximo, o sea una resonancia. Por eso las fₙ = ωₙ/2π se llaman frecuencias de resonancia (o eigenfrecuencias) y las δₙ son las constantes de amortiguamiento que fijan el ancho de cada pico.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.12), p. 54",
  },
  {
    id: "col-ku3-separacion",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 2,
    q: "En una sala rectangular de paredes rígidas, los kₓ permitidos valen…",
    opts: [
      "kₓ = nₓπ/Lₓ, con nₓ un entero no negativo cualquiera.",
      "kₓ = nₓc/2Lₓ, ya expresado directamente en hertz reales.",
      "cualquier valor real, sin cuantización por las paredes.",
      "kₓ = π/(2Lₓ), fijo e independiente del orden nₓ del modo.",
    ],
    ans: 0,
    why: "Con paredes rígidas la velocidad normal se anula en x = 0 y x = Lₓ, así que la solución es un coseno y la condición de tangente horizontal en ambos extremos obliga a kₓLₓ = múltiplo de π. Queda kₓ = nₓπ/Lₓ (e igual para y, z). Combinando los tres con kₓ²+k_y²+k_z² = k² se obtienen los autovalores y las eigenfrecuencias de la caja.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.18), p. 56",
  },
  {
    id: "col-ku3-planos-nodales",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 2,
    q: "En un modo (nₓ,n_y,n_z), los enteros nₓ, n_y, n_z indican…",
    opts: [
      "el número de planos nodales perpendiculares a cada eje.",
      "la cantidad de reflexiones que sufre el modo por segundo.",
      "el orden de la fuente imagen que genera ese modo dado.",
      "los decibeles de caída del modo entre pared y pared.",
    ],
    ans: 0,
    why: "La autofunción es un producto de tres cosenos; la presión se anula donde alguno de ellos vale cero, formando planos nodales equidistantes perpendiculares a cada eje. El entero nₓ es justamente el número de planos nodales perpendiculares al eje x (y análogamente n_y, n_z). A ambos lados de un plano nodal la presión instantánea tiene signo opuesto.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.22), p. 56",
  },
  {
    id: "col-ku3-ocho-ondas",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "Un modo de una sala rectangular puede verse como la suma de…",
    opts: [
      "ocho ondas planas viajeras con distintas fases y signos.",
      "dos ondas esféricas que salen desde el centro de la sala.",
      "una única onda plana que rebota siempre en el mismo plano.",
      "infinitas ondas cilíndricas centradas en cada arista real.",
    ],
    ans: 0,
    why: "Escribiendo cada coseno como suma de dos exponenciales, la autofunción se reparte en ocho términos: ocho ondas planas viajeras cuyas direcciones surgen de las ocho combinaciones de signo de (±nₓ/Lₓ, ±n_y/Ly, ±n_z/Lz). Se cumple cos²θₓ + cos²θ_y + cos²θ_z = 1. Así el modo (onda estacionaria) equivale a ondas planas que se cruzan, base del puente onda–rayo.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.24), p. 57",
  },
  {
    id: "col-ku3-axial-tang-obli",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 2,
    q: "Un modo con un solo índice distinto de cero (p. ej. 2,0,0) es…",
    opts: [
      "axial: se propaga paralelo a una arista de la sala.",
      "oblicuo: viaja en diagonal usando las tres dimensiones.",
      "tangencial: corre paralelo a un par de paredes dado.",
      "difuso: no tiene ninguna dirección de propagación clara.",
    ],
    ans: 0,
    why: "Si solo un índice es distinto de cero, la propagación es paralela a un eje (a una arista): es un modo axial, el más fuerte. Con un índice nulo el modo es tangencial (paralelo a un par de paredes) y con los tres índices no nulos es oblicuo. Los axiales suelen dominar el rango grave de las salas pequeñas y son los que más problemas dan.",
    src: "Kuttruff, Room Acoustics, cap. 3, p. 58",
  },
  {
    id: "col-ku3-numero-modos",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "El número total de modos por debajo de una frecuencia f crece con…",
    opts: [
      "f³, como (4π/3)·V·(f/c)³, contando puntos en el octante.",
      "f², proporcional al área total de las paredes de la sala.",
      "f, de forma lineal con la frecuencia superior elegida.",
      "log f, muy despacio al subir en el eje de frecuencia.",
    ],
    ans: 0,
    why: "Interpretando kₓ,k_y,k_z como coordenadas de una red en el espacio k, contar modos hasta f equivale a medir el volumen del octante de esfera de radio k dividido por el volumen π³/V que ocupa cada punto. Sale N(f) = (4π/3)·V·(f/c)³, que crece con f³. Su derivada da la densidad modal (∝ f²), y por eso los modos se agolpan cada vez más rápido.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.26), p. 59",
  },
  {
    id: "col-ku3-correccion-modos",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "En salas chicas a baja frecuencia, contar solo el término en f³…",
    opts: [
      "subestima: faltan términos con la superficie y las aristas.",
      "sobrestima: el término cúbico cuenta modos que no existen.",
      "da el valor exacto, sin necesidad de ninguna corrección.",
      "solo falla si la sala tiene forma bastante irregular real.",
    ],
    ans: 0,
    why: "El término (4π/3)·V·(f/c)³ solo cuenta bien los modos oblicuos: los tangenciales (en los planos coordenados) y los axiales (en los ejes) están compartidos entre octantes y quedan subcontados. La fórmula corregida agrega (π/4)·S·(f/c)² y L·f/8c. En el ejemplo de Kuttruff, para 116 Hz el término cúbico da 10 modos y la fórmula completa da 21: la corrección no es opcional en salas chicas.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.29), p. 60",
  },
  {
    id: "col-ku3-forma-arbitraria",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "La fórmula del número de modos con f³ (límite de f grande) vale…",
    opts: [
      "para salas de forma cualquiera, no solo rectangulares.",
      "solo para la caja rectangular exacta, nunca para otra.",
      "solo si todas las paredes son perfectamente rígidas.",
      "solo por encima de la frecuencia de Schroeder de la sala.",
    ],
    ans: 0,
    why: "Aunque se dedujo para una caja, la fórmula N(f) = (4π/3)·V·(f/c)³ vale, en el límite de f grande, para cualquier forma de recinto: se puede pensar cualquier volumen como suma de muchas cajas pequeñas, y como la fórmula es lineal en V, los aportes se suman. Es el resultado de Weyl y solo depende del volumen, no de la geometría.",
    src: "Kuttruff, Room Acoustics, cap. 3, p. 60",
  },
  {
    id: "col-ku3-pared-masa-resorte",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "Frente a la pared rígida, una pared reactiva controlada por masa…",
    opts: [
      "sube el valor permitido de kₓ (Im ζ > 0, tipo masa).",
      "baja el valor permitido de kₓ igual que un resorte.",
      "deja kₓ idéntico al de la pared rígida en todo caso.",
      "vuelve kₓ real solo si la pared no tiene pérdidas.",
    ],
    ans: 0,
    why: "Para paredes casi rígidas (|ζ| ≫ 1), el corrimiento de kₓ es real si la impedancia es puramente reactiva. Si Im ζ > 0 (movimiento controlado por masa) el kₓ permitido sube respecto de la pared rígida; si Im ζ < 0 (pared con impedancia de resorte, compliante) el kₓ baja. Este corrimiento de kₓ es lo que desplaza las frecuencias propias, la base del modelado de Z como perturbación de frontera.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.34), p. 62",
  },
  {
    id: "col-ku3-paredes-con-perdida",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 2,
    q: "Con paredes que disipan energía (impedancia con parte real), el modo…",
    opts: [
      "ya no tiene nodos exactos: la presión no se anula del todo.",
      "conserva nodos perfectos, solo que corridos en el espacio.",
      "desaparece por completo apenas la pared absorbe un poco.",
      "duplica su frecuencia propia respecto de la pared rígida.",
    ],
    ans: 0,
    why: "Si la impedancia específica tiene parte real (hay pérdidas), kₓ se vuelve complejo y ya no existen nodos exactos: la amplitud de presión es distinta de cero en todos los puntos. Se entiende porque la pared disipa energía, que debe llegar mediante ondas viajeras hacia ella; una onda puramente estacionaria (con nodos perfectos) no transportaría esa energía.",
    src: "Kuttruff, Room Acoustics, cap. 3, p. 62",
  },
  {
    id: "col-ku3-residuos",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "El método de residuos ponderados que usa Kuttruff para el FEM parte de…",
    opts: [
      "multiplicar la ecuación por una función de prueba e integrar.",
      "medir la presión en cada nodo y ajustar una curva por mínimos.",
      "sortear rayos al azar y promediar su energía en cada nodo.",
      "resolver la ecuación de onda exacta en todos los puntos reales.",
    ],
    ans: 0,
    why: "En residuos ponderados se multiplica la ecuación de Helmholtz por una función de prueba (peso) v(r) y se integra sobre el volumen. Si valiera para toda v, el corchete sería cero (la ecuación exacta); con una solución aproximada queda un residuo, que el peso reparte por el dominio. Aplicando el teorema de Green aparece la condición de contorno y baja el orden de derivación: es la forma débil, base del FEM.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.36), p. 64",
  },
  {
    id: "col-ku3-funciones-forma",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 2,
    q: "En el FEM, cada «función de forma» φₙ está definida para valer…",
    opts: [
      "uno en su propio nodo y cero en todos los demás nodos.",
      "uno en toda la sala, como una constante global fija.",
      "cero en su nodo y uno en el resto de la malla dada.",
      "la presión exacta medida en el nodo correspondiente.",
    ],
    ans: 0,
    why: "La presión se aproxima como suma p ≈ Σ pₙφₙ(r), donde cada función de forma φₙ vale 1 en el nodo n y 0 en todos los demás; entre nodos se interpola (lineal en el caso simple). Así cada coeficiente pₙ es directamente la presión aproximada en ese nodo, y el soporte local de las φₙ es lo que vuelve rala la matriz del sistema.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.39), p. 64",
  },
  {
    id: "col-ku3-matrices",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "El sistema FEM (K − k²M + ikC)·p = … tiene matrices que son…",
    opts: [
      "ralas y en banda: casi todo cero cerca de la diagonal.",
      "totalmente llenas, con casi todos sus elementos no nulos.",
      "diagonales exactas, sin términos fuera de la diagonal.",
      "antisimétricas, con la diagonal principal siempre nula.",
    ],
    ans: 0,
    why: "K (rigidez), M (masa) y C (amortiguamiento por la impedancia de pared) resultan ralas: un elemento es no nulo solo si dos nodos comparten elemento, y como cada nodo conecta con pocos vecinos, casi todo es cero. Con una numeración adecuada de nodos, los no nulos quedan en una banda angosta alrededor de la diagonal, lo que hace muy eficiente resolver el sistema.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.41), p. 65",
  },
  {
    id: "col-ku3-nodos-por-lambda",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 2,
    q: "Como regla práctica, un FEM acústico necesita, por longitud de onda…",
    opts: [
      "del orden de 3 a 10 nodos, y por eso escala mal arriba.",
      "un solo nodo, sin importar la frecuencia de trabajo.",
      "unos 100 nodos fijos, igual en graves que en agudos.",
      "nodos solo sobre las paredes, nunca dentro del volumen.",
    ],
    ans: 0,
    why: "La exactitud depende de la densidad de nodos: la literatura recomienda de 3 a 10 nodos por longitud de onda. Como λ baja con la frecuencia, el número de nodos crece rápido: en el ejemplo de Kuttruff, subir volumen o frecuencia ×10 lleva de ~320 a ~320.000 nodos. Por eso el FEM es práctico solo a baja frecuencia y en salas no muy grandes, justo el régimen bajo Schroeder.",
    src: "Kuttruff, Room Acoustics, cap. 3, p. 66",
  },
  {
    id: "col-ku3-maximos-no-modos",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "Por encima de fs, los máximos de la curva de frecuencia se deben a…",
    opts: [
      "coincidencias de fase casuales, no a resonancias sueltas.",
      "una única resonancia modal aislada en cada máximo dado.",
      "reflexiones especulares en las dos paredes más grandes.",
      "la absorción del aire, que realza ciertas frecuencias.",
    ],
    ans: 0,
    why: "Por encima de la frecuencia de Schroeder, en cada frecuencia se superponen muchos modos con fases al azar (fasores en el diagrama de Kuttruff). Un máximo aparece cuando muchos fasores apuntan casi igual y un mínimo cuando se cancelan: son coincidencias de fase accidentales, no resonancias individuales. Por eso mover la frecuencia o el punto de medición cambia por completo el detalle de la curva.",
    src: "Kuttruff, Room Acoustics, cap. 3, p. 69",
  },

  // ─── Cap. 3: Ondas en la sala (completar el capítulo, 20 preguntas más) ───
  {
    id: "col-ku3b-Dn-resonancia",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "En la solución modal, el coeficiente Dₙ = iρ₀ω·Cₙ/(kₙ²−k²) se dispara…",
    opts: [
      "cuando k se acerca a un autovalor kₙ de la sala.",
      "cuando la fuente se ubica sobre una pared rígida.",
      "cuando el volumen de la sala tiende a infinito real.",
      "cuando el modo tiene los tres índices iguales a cero.",
    ],
    ans: 0,
    why: "Al desarrollar fuente y solución en modos, cada coeficiente queda Dₙ = iρ₀ω·Cₙ/(kₙ²−k²). El denominador se anula cuando la frecuencia de excitación (vía k = ω/c) se acerca a un autovalor kₙ: ese término domina la suma y el modo entra en resonancia. Es el origen matemático de los picos de la función de transferencia de la sala.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.9), p. 53",
  },
  {
    id: "col-ku3b-fourier-fuente",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 2,
    q: "Si la fuente no es sinusoidal sino un espectro, la presión p(r,t) se arma…",
    opts: [
      "como integral de Fourier de las respuestas por frecuencia.",
      "sumando en fase las reflexiones especulares del recinto real.",
      "promediando la energía de muchos rayos sorteados al azar.",
      "resolviendo la ecuación de onda directa paso a paso en t.",
    ],
    ans: 0,
    why: "La respuesta a cada componente espectral está dada por la solución armónica (Ec. 3.10 o 3.12). Por linealidad, para una señal cualquiera se descompone la fuente en su espectro Q(ω), se pesa cada respuesta modal y se recompone con la integral de Fourier. La respuesta al impulso (transformada de la función de transferencia) es el caso límite de esto.",
    src: "Kuttruff, Room Acoustics, cap. 3, p. 54",
  },
  {
    id: "col-ku3b-eigenfrecuencia",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 2,
    q: "La eigenfrecuencia de un modo (nₓ,n_y,n_z) de una caja rígida es…",
    opts: [
      "f = (c/2)·√((nₓ/Lₓ)² + (n_y/L_y)² + (n_z/L_z)²) exacta.",
      "f = c·(nₓ/Lₓ + n_y/L_y + n_z/L_z), suma directa lineal.",
      "f = (c/2)·(nₓ + n_y + n_z), sin las dimensiones dadas.",
      "f = c/(2·V), fija e igual para todos los modos reales.",
    ],
    ans: 0,
    why: "De f = c·k/(2π) y k_{nx,ny,nz} = π·√((nₓ/Lₓ)²+(n_y/L_y)²+(n_z/L_z)²) sale la fórmula clásica f = (c/2)·√((nₓ/Lₓ)²+(n_y/L_y)²+(n_z/L_z)²). Los axiales dan las frecuencias más bajas (un solo índice), y a partir de ahí las combinaciones se agolpan. Es la base de todo cálculo de modos en salas rectangulares.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.23), p. 56",
  },
  {
    id: "col-ku3b-espaciado",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "El espaciado medio entre eigenfrecuencias vecinas, δfₙ = c³/(4πV·f²)…",
    opts: [
      "cae con f²: a alta frecuencia los modos casi se tocan.",
      "crece con f²: a alta frecuencia se separan cada vez más.",
      "es constante: la misma separación en todo el espectro.",
      "no depende para nada del volumen de la sala considerada.",
    ],
    ans: 0,
    why: "El espaciado medio es el inverso de la densidad modal: δfₙ = c³/(4πV·f²). Como cae con f², a alta frecuencia los modos se juntan tanto que dejan de distinguirse. En una sala grande a 1000 Hz el espaciado es menor a 0,0002 Hz: por eso arriba de Schroeder no tiene sentido calcular modos uno por uno y manda la estadística.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.28), p. 59",
  },
  {
    id: "col-ku3b-transcendental",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "Con paredes no rígidas, la ecuación que fija los kₓ permitidos es…",
    opts: [
      "transcendental: en general se resuelve en forma numérica.",
      "lineal: se despeja kₓ con una fórmula cerrada muy simple.",
      "idéntica a la de la pared rígida, sin ningún cambio real.",
      "independiente de la impedancia específica de esa pared.",
    ],
    ans: 0,
    why: "Con impedancia de pared finita, imponer la condición de contorno lleva a exp(ikₓLₓ) = ±(kₓζ−k)/(kₓζ+k), una ecuación transcendental que en general se resuelve numéricamente. Solo en el límite de pared casi rígida (|ζ|≫1) se puede aproximar y obtener el corrimiento de kₓ respecto del valor de la caja rígida.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.32), p. 61",
  },
  {
    id: "col-ku3b-forma-debil-bc",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "Tras aplicar el teorema de Green, la forma débil del FEM contiene…",
    opts: [
      "la ecuación de Helmholtz y la condición de contorno juntas.",
      "solo la ecuación de Helmholtz, sin la condición de borde.",
      "solo la condición de borde, sin la ecuación de Helmholtz.",
      "la ecuación de onda en el tiempo, ya sin la frecuencia.",
    ],
    ans: 0,
    why: "Al aplicar el teorema integral de Green a la ecuación de residuos ponderados aparece una integral de superficie, donde se sustituye la derivada normal por la impedancia de pared (condición de contorno 3.4). Así la forma débil contiene a la vez la ecuación de Helmholtz y la condición de contorno, y baja el orden de derivación de segundo a primero.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.38), p. 64",
  },
  {
    id: "col-ku3b-ensamblaje",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 2,
    q: "Las matrices globales K, M y C del FEM se calculan…",
    opts: [
      "elemento por elemento y luego se ensamblan sumando aportes.",
      "de una sola vez, integrando sobre todo el volumen junto.",
      "midiendo la presión en cada nodo con un micrófono real.",
      "solo sobre la superficie, nunca dentro del volumen dado.",
    ],
    ans: 0,
    why: "Primero se integran las contribuciones sobre cada elemento (matrices de elemento), luego se expanden a la posición correcta de la matriz global N×N y se suman todas. Este ensamblaje elemento por elemento, con una numeración global de nodos, es lo que permite armar sistemas de cientos de miles de elementos de forma ordenada y eficiente.",
    src: "Kuttruff, Room Acoustics, cap. 3, p. 65",
  },
  {
    id: "col-ku3b-fem-fdm-bem",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "Frente al FDM y al BEM, la ventaja propia del FEM es que…",
    opts: [
      "sus elementos se adaptan en forma y tamaño a la geometría.",
      "usa siempre una grilla regular de nodos, como el FDM.",
      "resuelve todo solo sobre la frontera, como hace el BEM.",
      "no necesita mallar el interior del recinto en ningún caso.",
    ],
    ans: 0,
    why: "El método de diferencias finitas (FDM) usa una grilla regular de nodos; el de elementos de frontera (BEM) resuelve sobre la superficie y de ahí obtiene el interior. La ventaja del FEM es que la forma y el tamaño de sus elementos se adaptan a la geometría del problema, refinando donde hace falta más exactitud. Los tres son numéricos y aproximados.",
    src: "Kuttruff, Room Acoustics, cap. 3, p. 66",
  },
  {
    id: "col-ku3b-ancho-banda",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "El ancho de banda a mitad de potencia de una resonancia es (Δf)ₙ = δₙ/π…",
    opts: [
      "y en salas grandes ronda 1 Hz para δ entre 1 y 20 s⁻¹.",
      "y crece rápido con la frecuencia propia del modo dado.",
      "y es siempre mucho mayor que el espaciado modal medio.",
      "y no guarda relación con la constante de amortiguar.",
    ],
    ans: 0,
    why: "Cada resonancia se comporta como un sistema resonante de ancho a mitad de potencia (Δf)ₙ = δₙ/π. Con las constantes de amortiguamiento típicas de salas reales (δ entre 1 y 20 s⁻¹), ese ancho es del orden de 1 Hz. Comparar ese ancho con el espaciado medio de modos es justo lo que define la frecuencia de Schroeder.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.43), p. 67",
  },
  {
    id: "col-ku3b-Nfs",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "El número de modos por debajo de la frecuencia de Schroeder vale…",
    opts: [
      "unos 800·√(T³/V): decenas de modos en una sala chica.",
      "unos 800·V³/T: millones de modos hasta en una chica.",
      "siempre menos de diez modos, sea cual sea la sala real.",
      "el mismo que el número total de modos de toda la sala.",
    ],
    ans: 0,
    why: "Metiendo la frecuencia de Schroeder en la fórmula del número de modos sale Nfs ≈ 800·√(T³/V). En un aula de 200 m³ con T = 1 s hay unos 60-70 modos por debajo de fs (≈140 Hz): son esos pocos modos los que dominan la acústica del rango grave, y por eso las salas chicas son, en cierto modo, más complicadas que las grandes.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.45), p. 67",
  },
  {
    id: "col-ku3b-acusticamente-grande",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "El criterio de sala «acústicamente grande» a una frecuencia f…",
    opts: [
      "depende de la frecuencia: sube el umbral al bajar en f.",
      "es un volumen fijo, el mismo para cualquier frecuencia.",
      "solo depende de la forma, no del volumen ni de la f real.",
      "coincide con que la sala pase los mil metros cúbicos.",
    ],
    ans: 0,
    why: "La condición fs = criterio se puede leer al revés: una sala es «acústicamente grande» si V supera cierto umbral que crece al bajar la frecuencia f. O sea, la misma sala es «grande» en agudos y «chica» en graves. El carácter modal o difuso no es del recinto en abstracto, sino del recinto a una frecuencia dada.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.46), p. 68",
  },
  {
    id: "col-ku3b-gaussiano",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "Por encima de fs, la presión en un punto tiene partes real e imaginaria…",
    opts: [
      "gaussianas, por el teorema central del límite aplicado.",
      "constantes, fijadas por el modo dominante de la sala.",
      "siempre en fase, sin ninguna dispersión estadística.",
      "distribuidas de forma uniforme entre cero y un máximo.",
    ],
    ans: 0,
    why: "Arriba de Schroeder la presión es la suma de muchos términos modales independientes con fases al azar. Por el teorema central del límite, tanto la parte real como la imaginaria de la presión resultante siguen una distribución gaussiana. De ahí se deduce que la densidad de energía sigue una ley exponencial, base de toda la acústica estadística de salas.",
    src: "Kuttruff, Room Acoustics, cap. 3, p. 68",
  },
  {
    id: "col-ku3b-exponencial",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "La distribución de la densidad de energía (arriba de fs) es exponencial y…",
    opts: [
      "no depende del volumen ni de la forma ni del tratamiento.",
      "cambia mucho según la forma y el tamaño de cada sala dada.",
      "solo vale en salas rectangulares de paredes muy rígidas.",
      "tiene media cero y varianza infinita en todos los casos.",
    ],
    ans: 0,
    why: "La cantidad y = |p|²/⟨|p|²⟩ se distribuye según P(y) = exp(−y), con media y varianza iguales a 1. Lo notable es que esta distribución es universal: no depende del volumen, la forma ni del tratamiento acústico de la sala. La probabilidad de superar un umbral y₀ es exp(−y₀), útil para estimar máximos en refuerzo sonoro.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.47), p. 68",
  },
  {
    id: "col-ku3b-maling",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "La potencia que una fuente puntual entrega a una sala, arriba de fs…",
    opts: [
      "es la misma que radiaría en campo libre (Maling).",
      "es siempre mayor que en campo libre, por los rebotes.",
      "depende fuerte de la posición exacta de la fuente.",
      "cae a cero porque la sala refleja toda la energía.",
    ],
    ans: 0,
    why: "Maling mostró, partiendo de la función de Green de la sala, que con solapamiento fuerte de modos (arriba de fs) la potencia emitida por una fuente puntual es la misma que en campo libre. Se entiende porque cerca de la fuente domina la onda esférica primaria y las distorsiones del recinto son despreciables. El resultado se generaliza a cualquier forma de sala.",
    src: "Kuttruff, Room Acoustics, cap. 3, p. 69",
  },
  {
    id: "col-ku3b-autocorr-espacial",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "En un campo difuso, la autocorrelación espacial de la energía va como…",
    opts: [
      "1 + (sen(kΔx)/kΔx)²: decae al alejar los dos puntos.",
      "crece sin límite con la distancia entre los dos puntos.",
      "es constante: los dos puntos siempre están correlados.",
      "cero salvo en Δx = 0, sin ninguna estructura espacial.",
    ],
    ans: 0,
    why: "La autocorrelación espacial de la respuesta energética en un campo difuso es ρ(Δx) = 1 + (sen(kΔx)/kΔx)². Mientras se aparta de 1, aún hay relación causal entre dos muestras separadas Δx; a partir de cierta distancia se vuelven independientes. Por eso el promedio espacial reduce la varianza, y de ahí sale la separación típica de máximos ≈ 0,79·λ.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.49), p. 70",
  },
  {
    id: "col-ku3b-Lmax",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 2,
    q: "El máximo absoluto de una curva de frecuencia, sobre la media, ronda…",
    opts: [
      "unos 10 dB en la mayoría de las situaciones prácticas.",
      "unos 60 dB, igual que la caída total de reverberación.",
      "menos de 1 dB, es decir, la curva es casi del todo plana.",
      "un valor que crece sin ningún tope con el ancho de banda.",
    ],
    ans: 0,
    why: "El máximo absoluto de una curva de frecuencia dentro de un ancho de banda B se estima como Lmax = 4,34·ln[ln(BT)] + 3,6 dB (fórmula tipo Schroeder). Como depende del doble logaritmo, es poco sensible a B, y en la práctica ronda los 10 dB. Es un dato clave para la estabilidad de sistemas de refuerzo sonoro (realimentación).",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.53), p. 71",
  },
  {
    id: "col-ku3b-varianza-M",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "Al excitar la sala con M tonos bien separados, la varianza relativa…",
    opts: [
      "baja como 1/M: promediar suaviza la respuesta de la sala.",
      "sube como M: sumar más tonos empeora mucho la dispersión.",
      "queda igual a 1, sin importar cuántos tonos se usen ahí.",
      "solo baja si los tonos están bien juntos en frecuencia.",
    ],
    ans: 0,
    why: "Excitar con M tonos de frecuencias bien separadas (o promediar M puntos separados del campo) hace que la varianza relativa de la respuesta energética baje como 1/M. Es el mismo mecanismo del promedio espacial o en frecuencia: suaviza la curva irregular de la sala. Justifica medir con ruido de banda o promediando posiciones.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.55), p. 73",
  },
  {
    id: "col-ku3b-impulso-decae",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "La respuesta al impulso de la sala es una suma de…",
    opts: [
      "senoides amortiguadas, cada una con su propio decaimiento.",
      "una sola senoide pura que decae con un tiempo bien fijo.",
      "rebotes especulares limpios y sin ninguna pérdida de energía.",
      "ruido blanco constante hasta que se apaga todo de golpe.",
    ],
    ans: 0,
    why: "La respuesta al impulso g(t) es la transformada de Fourier de la función de transferencia: una suma de oscilaciones senoidales, cada una con su frecuencia ωₙ y su propia constante de amortiguamiento δₙ. Es natural, porque cada modo es un resonador cuya respuesta a un impulso es una oscilación amortiguada. Al elevar al cuadrado y promediar se obtiene la energía que decae.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.60), p. 75",
  },
  {
    id: "col-ku3b-decay-recto",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "La curva de decaimiento (nivel vs tiempo) es una recta perfecta solo si…",
    opts: [
      "todas las constantes de amortiguamiento son iguales.",
      "la sala tiene forma perfectamente cúbica y rígida.",
      "hay un solo modo excitado por debajo de Schroeder.",
      "la fuente y el receptor están muy cerca uno del otro.",
    ],
    ans: 0,
    why: "El decaimiento se describe con una densidad de constantes de amortiguamiento H(δ). La pendiente inicial es proporcional a la media de H(δ) y la curvatura inicial a su varianza; se demuestra que la curva siempre se dobla hacia arriba (o es recta). Solo cuando todas las δ son iguales (varianza cero) el decaimiento es una recta exacta.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.69), p. 77",
  },
  {
    id: "col-ku3b-maximos-espaciales",
    seccion: "Cap. 3: Ondas en la sala", cat: "Cap. 3: Ondas en la sala", dif: 3,
    q: "La distancia media entre máximos de una curva espacial, en campo difuso, es…",
    opts: [
      "de unos 0,79·λ: escala con la longitud de onda del sonido.",
      "de media longitud de onda exacta, es decir λ/2 siempre.",
      "de una longitud de onda completa, λ, fija en toda sala.",
      "del todo independiente de la longitud de onda del sonido.",
    ],
    ans: 0,
    why: "Recorriendo un micrófono en línea recta a frecuencia fija se obtiene la «curva espacial»: irregular, con máximos y valles. En campo difuso, la distancia media entre máximos vecinos es Δxmax ≈ 0,79·λ, o sea del orden de la longitud de onda. Es el análogo espacial del espaciado de máximos de la curva de frecuencia, y explica por qué basta mover el micrófono ~λ para descorrelacionar la medición.",
    src: "Kuttruff, Room Acoustics, cap. 3 (Ec. 3.51), p. 71",
  },

].map((q) => ({ ...q, fuente: "kuttruff-ra" }));
